"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager

logger = ...
class CursorWrapper:
    def __init__(self, cursor, db) -> None:
        ...
    
    WRAP_ERROR_ATTRS = ...
    def __getattr__(self, attr):
        ...
    
    def __iter__(self):
        ...
    
    def __enter__(self):
        ...
    
    def __exit__(self, type, value, traceback):
        ...
    
    def callproc(self, procname, params=..., kparams=...):
        ...
    
    def execute(self, sql, params=...):
        ...
    
    def executemany(self, sql, param_list):
        ...
    


class CursorDebugWrapper(CursorWrapper):
    def execute(self, sql, params=...):
        ...
    
    def executemany(self, sql, param_list):
        ...
    
    @contextmanager
    def debug_sql(self, sql=..., params=..., use_last_executed_query=..., many=...):
        ...
    


def typecast_date(s):
    ...

def typecast_time(s):
    ...

def typecast_timestamp(s):
    ...

def split_identifier(identifier):
    """
    Split an SQL identifier into a two element tuple of (namespace, name).

    The identifier could be a table, column, or sequence name might be prefixed
    by a namespace.
    """
    ...

def truncate_name(identifier, length=..., hash_len=...):
    """
    Shorten an SQL identifier to a repeatable mangled version with the given
    length.

    If a quote stripped name contains a namespace, e.g. USERNAME"."TABLE,
    truncate the table portion only.
    """
    ...

def names_digest(*args, length):
    """
    Generate a 32-bit digest of a set of arguments that can be used to shorten
    identifying names.
    """
    ...

def format_number(value, max_digits, decimal_places):
    """
    Format a number into a string with the requisite number of digits and
    decimal places.
    """
    ...

def strip_quotes(table_name):
    """
    Strip quotes off of quoted table names to make them safe for use in index
    names, sequence names, etc. For example '"USER"."TABLE"' (an Oracle naming
    scheme) becomes 'USER"."TABLE'.
    """
    ...

