"""
This type stub file was generated by pyright.
"""

from OpenGL import platform as _p
from OpenGL.raw.GL import _types as _cs
from OpenGL.raw.GL._types import *

"""
This type stub file was generated by pyright.
"""
_EXTENSION_NAME = ...
@_f
@_p.types(None, _cs.GLenum, _cs.GLuint, _cs.GLsizei)
def glDrawTransformFeedbackInstanced(mode, id, instancecount):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLuint, _cs.GLuint, _cs.GLsizei)
def glDrawTransformFeedbackStreamInstanced(mode, id, stream, instancecount):
    ...

