"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL._types import *

'''Autogenerated by xml_generate script, do not edit!'''
_EXTENSION_NAME = ...
GL_DEPTH_STENCIL_TEXTURE_MODE = ...
