"""
This type stub file was generated by pyright.
"""

from OpenGL import platform as _p
from OpenGL.raw.GL import _types as _cs
from OpenGL.raw.GL._types import *

'''Autogenerated by xml_generate script, do not edit!'''
_EXTENSION_NAME = ...
GL_TEXTURE_BUFFER_OFFSET = ...
GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT = ...
GL_TEXTURE_BUFFER_SIZE = ...
@_f
@_p.types(None, _cs.GLenum, _cs.GLenum, _cs.GLuint, _cs.GLintptr, _cs.GLsizeiptr)
def glTexBufferRange(target, internalformat, buffer, offset, size):
    ...

