"""
This type stub file was generated by pyright.
"""

import ctypes
from OpenGL import arrays, platform as _p
from OpenGL.raw.GL import _types as _cs
from OpenGL.raw.GL._types import *

'''Autogenerated by xml_generate script, do not edit!'''
_EXTENSION_NAME = ...
GL_CURRENT_VERTEX_ATTRIB_ARB = ...
GL_FLOAT = ...
GL_FLOAT_MAT2_ARB = ...
GL_FLOAT_MAT3_ARB = ...
GL_FLOAT_MAT4_ARB = ...
GL_FLOAT_VEC2_ARB = ...
GL_FLOAT_VEC3_ARB = ...
GL_FLOAT_VEC4_ARB = ...
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS_ARB = ...
GL_MAX_TEXTURE_COORDS_ARB = ...
GL_MAX_TEXTURE_IMAGE_UNITS_ARB = ...
GL_MAX_VARYING_FLOATS_ARB = ...
GL_MAX_VERTEX_ATTRIBS_ARB = ...
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS_ARB = ...
GL_MAX_VERTEX_UNIFORM_COMPONENTS_ARB = ...
GL_OBJECT_ACTIVE_ATTRIBUTES_ARB = ...
GL_OBJECT_ACTIVE_ATTRIBUTE_MAX_LENGTH_ARB = ...
GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB = ...
GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB = ...
GL_VERTEX_ATTRIB_ARRAY_POINTER_ARB = ...
GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB = ...
GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB = ...
GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB = ...
GL_VERTEX_PROGRAM_POINT_SIZE_ARB = ...
GL_VERTEX_PROGRAM_TWO_SIDE_ARB = ...
GL_VERTEX_SHADER_ARB = ...
@_f
@_p.types(None, _cs.GLhandleARB, _cs.GLuint, arrays.GLcharARBArray)
def glBindAttribLocationARB(programObj, index, name):
    ...

@_f
@_p.types(None, _cs.GLuint)
def glDisableVertexAttribArrayARB(index):
    ...

@_f
@_p.types(None, _cs.GLuint)
def glEnableVertexAttribArrayARB(index):
    ...

@_f
@_p.types(None, _cs.GLhandleARB, _cs.GLuint, _cs.GLsizei, arrays.GLsizeiArray, arrays.GLintArray, arrays.GLuintArray, arrays.GLcharARBArray)
def glGetActiveAttribARB(programObj, index, maxLength, length, size, type, name):
    ...

@_f
@_p.types(_cs.GLint, _cs.GLhandleARB, arrays.GLcharARBArray)
def glGetAttribLocationARB(programObj, name):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLvoidpArray)
def glGetVertexAttribPointervARB(index, pname, pointer):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLdoubleArray)
def glGetVertexAttribdvARB(index, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLfloatArray)
def glGetVertexAttribfvARB(index, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLintArray)
def glGetVertexAttribivARB(index, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLdouble)
def glVertexAttrib1dARB(index, x):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLdoubleArray)
def glVertexAttrib1dvARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLfloat)
def glVertexAttrib1fARB(index, x):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLfloatArray)
def glVertexAttrib1fvARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLshort)
def glVertexAttrib1sARB(index, x):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLshortArray)
def glVertexAttrib1svARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLdouble, _cs.GLdouble)
def glVertexAttrib2dARB(index, x, y):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLdoubleArray)
def glVertexAttrib2dvARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLfloat, _cs.GLfloat)
def glVertexAttrib2fARB(index, x, y):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLfloatArray)
def glVertexAttrib2fvARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLshort, _cs.GLshort)
def glVertexAttrib2sARB(index, x, y):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLshortArray)
def glVertexAttrib2svARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLdouble, _cs.GLdouble, _cs.GLdouble)
def glVertexAttrib3dARB(index, x, y, z):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLdoubleArray)
def glVertexAttrib3dvARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLfloat, _cs.GLfloat, _cs.GLfloat)
def glVertexAttrib3fARB(index, x, y, z):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLfloatArray)
def glVertexAttrib3fvARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLshort, _cs.GLshort, _cs.GLshort)
def glVertexAttrib3sARB(index, x, y, z):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLshortArray)
def glVertexAttrib3svARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLbyteArray)
def glVertexAttrib4NbvARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLintArray)
def glVertexAttrib4NivARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLshortArray)
def glVertexAttrib4NsvARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLubyte, _cs.GLubyte, _cs.GLubyte, _cs.GLubyte)
def glVertexAttrib4NubARB(index, x, y, z, w):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLubyteArray)
def glVertexAttrib4NubvARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLuintArray)
def glVertexAttrib4NuivARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLushortArray)
def glVertexAttrib4NusvARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLbyteArray)
def glVertexAttrib4bvARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLdouble, _cs.GLdouble, _cs.GLdouble, _cs.GLdouble)
def glVertexAttrib4dARB(index, x, y, z, w):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLdoubleArray)
def glVertexAttrib4dvARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLfloat, _cs.GLfloat, _cs.GLfloat, _cs.GLfloat)
def glVertexAttrib4fARB(index, x, y, z, w):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLfloatArray)
def glVertexAttrib4fvARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLintArray)
def glVertexAttrib4ivARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLshort, _cs.GLshort, _cs.GLshort, _cs.GLshort)
def glVertexAttrib4sARB(index, x, y, z, w):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLshortArray)
def glVertexAttrib4svARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLubyteArray)
def glVertexAttrib4ubvARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLuintArray)
def glVertexAttrib4uivARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLushortArray)
def glVertexAttrib4usvARB(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLenum, _cs.GLboolean, _cs.GLsizei, ctypes.c_void_p)
def glVertexAttribPointerARB(index, size, type, normalized, stride, pointer):
    ...

