"""
This type stub file was generated by pyright.
"""

from OpenGL._bytes import bytes, long

"""
This type stub file was generated by pyright.
"""
class Constant(object):
    """OpenGL constant that displays itself as a name rather than a value

    The purpose of this class is to make debugging OpenGL code easier,
    as you recieve messages that say what value you passed in in a
    human-readable form, rather than as a bald number that requires
    lookup and disambiguation in the header file.
    """
    def __new__(cls, name, value=...):
        """Initialise the constant with the given name and value"""
        ...
    
    def __repr__(self):
        """Return the name, rather than the bald value"""
        ...
    
    def __getnewargs__(self):
        """Produce the new arguments for recreating the instance"""
        ...
    


class NumericConstant(Constant):
    """Base class for numeric-value constants"""
    def __str__(self) -> str:
        """Return the value as a human-friendly string"""
        ...
    
    def __getstate__(self):
        """Retrieve state for pickle and the like"""
        ...
    
    def __setstate__(self, state):
        ...
    


class IntConstant(NumericConstant, int):
    """Integer constant"""
    ...


if int is not long:
    class LongConstant(NumericConstant, long):
        """Long integer constant"""
        ...
    
    
else:
    LongConstant = ...
class FloatConstant(NumericConstant, float):
    """Float constant"""
    ...


class StringConstant(Constant, bytes):
    """String constants"""
    def __repr__(self):
        """Return the value as a human-friendly string"""
        ...
    


if __name__ == "__main__":
    x = ...
    y = ...
    z = ...
