"""
This type stub file was generated by pyright.
"""

from OpenGL import platform as _p
from OpenGL.raw.GL import _types as _cs
from OpenGL.raw.GL._types import *

"""
This type stub file was generated by pyright.
"""
_EXTENSION_NAME = ...
GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_EXT = ...
GL_MAX_SAMPLES_EXT = ...
GL_RENDERBUFFER_SAMPLES_EXT = ...
@_f
@_p.types(None, _cs.GLenum, _cs.GLsizei, _cs.GLenum, _cs.GLsizei, _cs.GLsizei)
def glRenderbufferStorageMultisampleEXT(target, samples, internalformat, width, height):
    ...

