"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.arrays_of_arrays import *

"""
This type stub file was generated by pyright.
"""
def glInitArraysOfArraysARB():
    '''Return boolean indicating whether this extension is available'''
    ...

