"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.clear_buffer_object import *

"""
This type stub file was generated by pyright.
"""
def glInitClearBufferObjectARB():
    '''Return boolean indicating whether this extension is available'''
    ...

glClearBufferData = ...
glClearBufferSubData = ...
