"""
This type stub file was generated by pyright.
"""

from OpenGL import lazywrapper as _lazywrapper
from OpenGL.raw.GL.ARB.ES2_compatibility import *

"""
This type stub file was generated by pyright.
"""
def glInitEs2CompatibilityARB():
    '''Return boolean indicating whether this extension is available'''
    ...

glShaderBinary = ...
glGetShaderPrecisionFormat = ...
@_lazywrapper.lazy(glGetShaderPrecisionFormat)
def glGetShaderPrecisionFormat(baseOperation, shadertype, precisiontype, range=..., precision=...):
    """Provides range and precision if not provided, returns (range,precision)"""
    ...

