"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.ES3_compatibility import *

"""
This type stub file was generated by pyright.
"""
def glInitEs3CompatibilityARB():
    '''Return boolean indicating whether this extension is available'''
    ...

