"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.internalformat_query import *

"""
This type stub file was generated by pyright.
"""
def glInitInternalformatQueryARB():
    '''Return boolean indicating whether this extension is available'''
    ...

glGetInternalformativ = ...
