"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.invalidate_subdata import *

"""
This type stub file was generated by pyright.
"""
def glInitInvalidateSubdataARB():
    '''Return boolean indicating whether this extension is available'''
    ...

glInvalidateFramebuffer = ...
glInvalidateSubFramebuffer = ...
