"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.shader_atomic_counters import *

"""
This type stub file was generated by pyright.
"""
def glInitShaderAtomicCountersARB():
    '''Return boolean indicating whether this extension is available'''
    ...

glGetActiveAtomicCounterBufferiv = ...
