"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.shader_storage_buffer_object import *

"""
This type stub file was generated by pyright.
"""
def glInitShaderStorageBufferObjectARB():
    '''Return boolean indicating whether this extension is available'''
    ...

