"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.texture_storage_multisample import *

"""
This type stub file was generated by pyright.
"""
def glInitTextureStorageMultisampleARB():
    '''Return boolean indicating whether this extension is available'''
    ...

