"""
This type stub file was generated by pyright.
"""

from OpenGL.arrays import vbo

"""
This type stub file was generated by pyright.
"""
class Implementation(vbo.Implementation):
    """OpenGL ARB extension-based implementation of VBO interfaces"""
    def __init__(self) -> None:
        ...
    


