"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.vertex_attrib_binding import *

"""
This type stub file was generated by pyright.
"""
def glInitVertexAttribBindingARB():
    '''Return boolean indicating whether this extension is available'''
    ...

