"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GLUT import *
from OpenGL.GLUT.special import *
from OpenGL.GLUT.fonts import *
from OpenGL.GLUT.freeglut import *
from OpenGL.GLUT.osx import *

"""
This type stub file was generated by pyright.
"""
if glutLeaveMainLoop:
    HAVE_FREEGLUT = ...
else:
    HAVE_FREEGLUT = ...
