"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.EXT.framebuffer_blit import *

"""
This type stub file was generated by pyright.
"""
def glInitFramebufferBlitEXT():
    '''Return boolean indicating whether this extension is available'''
    ...

