"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.EXT.framebuffer_multisample import *

"""
This type stub file was generated by pyright.
"""
def glInitFramebufferMultisampleEXT():
    '''Return boolean indicating whether this extension is available'''
    ...

