"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GLX.VERSION.GLX_1_4 import *

'''OpenGL extension VERSION.GLX_1_4

This module customises the behaviour of the 
OpenGL.raw.GLX.VERSION.GLX_1_4 to provide a more 
Python-friendly API

The official definition of this extension is available here:
http://www.opengl.org/registry/specs/VERSION/GLX_1_4.txt
'''
def glInitGlx14VERSION():
    '''Return boolean indicating whether this extension is available'''
    ...

