"""
This type stub file was generated by pyright.
"""

import functools

@functools.lru_cache(maxsize=None)
def get_default_password_validators():
    ...

def get_password_validators(validator_config):
    ...

def validate_password(password, user=..., password_validators=...):
    """
    Validate whether the password meets all validator requirements.

    If the password is valid, return ``None``.
    If the password is invalid, raise ValidationError with all error messages.
    """
    ...

def password_changed(password, user=..., password_validators=...):
    """
    Inform all validators that have implemented a password_changed() method
    that the password has been changed.
    """
    ...

def password_validators_help_texts(password_validators=...):
    """
    Return a list of all help texts of all configured validators.
    """
    ...

password_validators_help_text_html = ...
class MinimumLengthValidator:
    """
    Validate whether the password is of a minimum length.
    """
    def __init__(self, min_length=...) -> None:
        ...
    
    def validate(self, password, user=...):
        ...
    
    def get_help_text(self):
        ...
    


class UserAttributeSimilarityValidator:
    """
    Validate whether the password is sufficiently different from the user's
    attributes.

    If no specific attributes are provided, look at a sensible list of
    defaults. Attributes that don't exist are ignored. Comparison is made to
    not only the full attribute value, but also its components, so that, for
    example, a password is validated against either part of an email address,
    as well as the full address.
    """
    DEFAULT_USER_ATTRIBUTES = ...
    def __init__(self, user_attributes=..., max_similarity=...) -> None:
        ...
    
    def validate(self, password, user=...):
        ...
    
    def get_help_text(self):
        ...
    


class CommonPasswordValidator:
    """
    Validate whether the password is a common password.

    The password is rejected if it occurs in a provided list of passwords,
    which may be gzipped. The list Django ships with contains 20000 common
    passwords (lowercased and deduplicated), created by Royce Williams:
    https://gist.github.com/roycewilliams/281ce539915a947a23db17137d91aeb7
    The password list must be lowercased to match the comparison in validate().
    """
    DEFAULT_PASSWORD_LIST_PATH = ...
    def __init__(self, password_list_path=...) -> None:
        ...
    
    def validate(self, password, user=...):
        ...
    
    def get_help_text(self):
        ...
    


class NumericPasswordValidator:
    """
    Validate whether the password is alphanumeric.
    """
    def validate(self, password, user=...):
        ...
    
    def get_help_text(self):
        ...
    


