"""
This type stub file was generated by pyright.
"""

import numpy.linalg as linpkg
import numpy.fft as fftpkg

"""
This type stub file was generated by pyright.
"""
fft = fftpkg.fft
ifft = fftpkg.ifft
fftn = fftpkg.fftn
ifftn = fftpkg.ifftn
fft2 = fftpkg.fft2
ifft2 = fftpkg.ifft2
norm = linpkg.norm
inv = linpkg.inv
svd = linpkg.svd
solve = linpkg.solve
det = linpkg.det
eig = linpkg.eig
eigvals = linpkg.eigvals
eigh = linpkg.eigh
eigvalsh = linpkg.eigvalsh
lstsq = linpkg.lstsq
pinv = linpkg.pinv
cholesky = linpkg.cholesky
_restore_dict = ...
def register_func(name, func):
    ...

def restore_func(name):
    ...

def restore_all():
    ...

