"""
This type stub file was generated by pyright.
"""

from typing import Any, List

"""
This type stub file was generated by pyright.
"""
__all__: List[str]
record: Any
recarray: Any
format_parser: Any
fromarrays: Any
fromrecords: Any
fromstring: Any
fromfile: Any
array: Any
