"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.compute_shader import *

"""
This type stub file was generated by pyright.
"""
def glInitComputeShaderARB():
    '''Return boolean indicating whether this extension is available'''
    ...

