"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.conservative_depth import *

"""
This type stub file was generated by pyright.
"""
def glInitConservativeDepthARB():
    '''Return boolean indicating whether this extension is available'''
    ...

