"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.framebuffer_no_attachments import *

"""
This type stub file was generated by pyright.
"""
def glInitFramebufferNoAttachmentsARB():
    '''Return boolean indicating whether this extension is available'''
    ...

glGetFramebufferParameteriv = ...
