"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.multi_draw_indirect import *

"""
This type stub file was generated by pyright.
"""
def glInitMultiDrawIndirectARB():
    '''Return boolean indicating whether this extension is available'''
    ...

glMultiDrawArraysIndirect = ...
glMultiDrawElementsIndirect = ...
