"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.shading_language_420pack import *

"""
This type stub file was generated by pyright.
"""
def glInitShadingLanguage420PackARB():
    '''Return boolean indicating whether this extension is available'''
    ...

