"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.stencil_texturing import *

"""
This type stub file was generated by pyright.
"""
def glInitStencilTexturingARB():
    '''Return boolean indicating whether this extension is available'''
    ...

