"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.texture_buffer_range import *

"""
This type stub file was generated by pyright.
"""
def glInitTextureBufferRangeARB():
    '''Return boolean indicating whether this extension is available'''
    ...

