"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.texture_storage import *

"""
This type stub file was generated by pyright.
"""
def glInitTextureStorageARB():
    '''Return boolean indicating whether this extension is available'''
    ...

