"""
This type stub file was generated by pyright.
"""

from OpenGL import arrays, platform as _p
from OpenGL.raw.GL import _types as _cs
from OpenGL.raw.GL._types import *

"""
This type stub file was generated by pyright.
"""
_EXTENSION_NAME = ...
@_f
@_p.types(None, _cs.GLuint)
def glInvalidateBufferData(buffer):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLintptr, _cs.GLsizeiptr)
def glInvalidateBufferSubData(buffer, offset, length):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLsizei, arrays.GLuintArray)
def glInvalidateFramebuffer(target, numAttachments, attachments):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLsizei, arrays.GLuintArray, _cs.GLint, _cs.GLint, _cs.GLsizei, _cs.GLsizei)
def glInvalidateSubFramebuffer(target, numAttachments, attachments, x, y, width, height):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint)
def glInvalidateTexImage(texture, level):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLsizei, _cs.GLsizei, _cs.GLsizei)
def glInvalidateTexSubImage(texture, level, xoffset, yoffset, zoffset, width, height, depth):
    ...

