"""
This type stub file was generated by pyright.
"""

import re

COMPILED_REGEX_TYPE = type(re.compile(''))
class RegexObject:
    def __init__(self, obj) -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    


def get_migration_name_timestamp():
    ...

