"""
This type stub file was generated by pyright.
"""

from OpenGL.platform import PLATFORM as _p
from OpenGL.error import _ErrorChecker

if _p.GLES1 and _p.GLES1.glGetError and _ErrorChecker:
    _error_checker = ...
else:
    _error_checker = ...
