"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.base_instance import *

"""
This type stub file was generated by pyright.
"""
def glInitBaseInstanceARB():
    '''Return boolean indicating whether this extension is available'''
    ...

glDrawElementsInstancedBaseInstance = ...
glDrawElementsInstancedBaseVertexBaseInstance = ...
