"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.compressed_texture_pixel_storage import *

"""
This type stub file was generated by pyright.
"""
def glInitCompressedTexturePixelStorageARB():
    '''Return boolean indicating whether this extension is available'''
    ...

