"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.explicit_uniform_location import *

"""
This type stub file was generated by pyright.
"""
def glInitExplicitUniformLocationARB():
    '''Return boolean indicating whether this extension is available'''
    ...

