"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.fragment_layer_viewport import *

"""
This type stub file was generated by pyright.
"""
def glInitFragmentLayerViewportARB():
    '''Return boolean indicating whether this extension is available'''
    ...

