"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.get_program_binary import *

"""
This type stub file was generated by pyright.
"""
def glInitGetProgramBinaryARB():
    '''Return boolean indicating whether this extension is available'''
    ...

glGetProgramBinary = ...
glProgramBinary = ...
