"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.robust_buffer_access_behavior import *

"""
This type stub file was generated by pyright.
"""
def glInitRobustBufferAccessBehaviorARB():
    '''Return boolean indicating whether this extension is available'''
    ...

