"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.shader_image_size import *

"""
This type stub file was generated by pyright.
"""
def glInitShaderImageSizeARB():
    '''Return boolean indicating whether this extension is available'''
    ...

