"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.shader_image_load_store import *

"""
This type stub file was generated by pyright.
"""
def glInitShaderImageLoadStoreARB():
    '''Return boolean indicating whether this extension is available'''
    ...

