"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.texture_query_levels import *

"""
This type stub file was generated by pyright.
"""
def glInitTextureQueryLevelsARB():
    '''Return boolean indicating whether this extension is available'''
    ...

