"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.ARB.texture_view import *

"""
This type stub file was generated by pyright.
"""
def glInitTextureViewARB():
    '''Return boolean indicating whether this extension is available'''
    ...

