"""
This type stub file was generated by pyright.
"""

import os
import sys
from OpenGL.plugins import PlatformPlugin
from OpenGL import _configflags

"""
This type stub file was generated by pyright.
"""
def types(resultType, *argTypes):
    """Decorator to add returnType, argTypes and argNames to a function"""
    ...

def unpack_constants(constants, namespace):
    """Create constants and add to the namespace"""
    ...

def createFunction(function, dll, extension, deprecated=..., error_checker=..., force_extension=...):
    """Allows the more compact declaration format to use the old-style constructor"""
    ...

