"""
This type stub file was generated by pyright.
"""

import ctypes
from OpenGL import platform as _p
from OpenGL.raw.GLX import _types as _cs
from OpenGL.raw.GLX._types import *

"""
This type stub file was generated by pyright.
"""
_EXTENSION_NAME = ...
GLX_EXTENSIONS = ...
GLX_VENDOR = ...
GLX_VERSION = ...
@_f
@_p.types(ctypes.c_char_p, ctypes.POINTER(_cs.Display), _cs.c_int)
def glXGetClientString(dpy, name):
    ...

@_f
@_p.types(ctypes.c_char_p, ctypes.POINTER(_cs.Display), _cs.c_int)
def glXQueryExtensionsString(dpy, screen):
    ...

@_f
@_p.types(ctypes.c_char_p, ctypes.POINTER(_cs.Display), _cs.c_int, _cs.c_int)
def glXQueryServerString(dpy, screen, name):
    ...

