"""
This type stub file was generated by pyright.
"""

from ctypes import *

"""Array-size annotations for OpenGL.raw.GLUT

Automatically generated by the generateraw script, do not edit!
"""
GLvoid = ...
STRING = c_char_p
