"""
This type stub file was generated by pyright.
"""

import ctypes
from OpenGL import platform
from OpenGL.error import *
from OpenGL.raw.GLU import *
from OpenGL.raw.GLU.annotations import *
from OpenGL.GLU.quadrics import *
from OpenGL.GLU.projection import *
from OpenGL.GLU.tess import *
from OpenGL.GLU.glunurbs import *

"""The GLU library implementation via ctypes"""
