"""
This type stub file was generated by pyright.
"""

from OpenGL.raw import GLU as _simple
from OpenGL.lazywrapper import lazy as _lazy

"""glu[Un]Project[4] convenience wrappers"""
POINTER = ...
@_lazy(_simple.gluProject)
def gluProject(baseFunction, objX, objY, objZ, model=..., proj=..., view=...):
    """Convenience wrapper for gluProject
    
    Automatically fills in the model, projection and viewing matrices
    if not provided.
    
    returns (winX,winY,winZ) doubles
    """
    ...

@_lazy(_simple.gluUnProject)
def gluUnProject(baseFunction, winX, winY, winZ, model=..., proj=..., view=...):
    """Convenience wrapper for gluUnProject
    
    Automatically fills in the model, projection and viewing matrices
    if not provided.
    
    returns (objX,objY,objZ) doubles
    """
    ...

@_lazy(_simple.gluUnProject4)
def gluUnProject4(baseFunction, winX, winY, winZ, clipW, model=..., proj=..., view=..., near=..., far=...):
    """Convenience wrapper for gluUnProject
    
    Automatically fills in the model, projection and viewing matrices
    if not provided.
    
    returns (objX,objY,objZ) doubles
    """
    ...

