"""
This type stub file was generated by pyright.
"""

from enum import Enum

class BaseConstraint:
    def __init__(self, name) -> None:
        ...
    
    def constraint_sql(self, model, schema_editor):
        ...
    
    def create_sql(self, model, schema_editor):
        ...
    
    def remove_sql(self, model, schema_editor):
        ...
    
    def deconstruct(self):
        ...
    
    def clone(self):
        ...
    


class CheckConstraint(BaseConstraint):
    def __init__(self, *, check, name) -> None:
        ...
    
    def constraint_sql(self, model, schema_editor):
        ...
    
    def create_sql(self, model, schema_editor):
        ...
    
    def remove_sql(self, model, schema_editor):
        ...
    
    def __repr__(self):
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def deconstruct(self):
        ...
    


class Deferrable(Enum):
    DEFERRED = ...
    IMMEDIATE = ...


class UniqueConstraint(BaseConstraint):
    def __init__(self, *, fields, name, condition=..., deferrable=..., include=..., opclasses=...) -> None:
        ...
    
    def constraint_sql(self, model, schema_editor):
        ...
    
    def create_sql(self, model, schema_editor):
        ...
    
    def remove_sql(self, model, schema_editor):
        ...
    
    def __repr__(self):
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def deconstruct(self):
        ...
    


