"""
This type stub file was generated by pyright.
"""

from django.db.models.expressions import Func
from django.db.models.fields import Field, IntegerField, UUIDField
from django.db.models.query_utils import RegisterLookupMixin
from django.utils.functional import cached_property

class Lookup:
    lookup_name = ...
    prepare_rhs = ...
    can_use_none_as_rhs = ...
    def __init__(self, lhs, rhs) -> None:
        ...
    
    def apply_bilateral_transforms(self, value):
        ...
    
    def batch_process_rhs(self, compiler, connection, rhs=...):
        ...
    
    def get_source_expressions(self):
        ...
    
    def set_source_expressions(self, new_exprs):
        ...
    
    def get_prep_lookup(self):
        ...
    
    def get_db_prep_lookup(self, value, connection):
        ...
    
    def process_lhs(self, compiler, connection, lhs=...):
        ...
    
    def process_rhs(self, compiler, connection):
        ...
    
    def rhs_is_direct_value(self):
        ...
    
    def relabeled_clone(self, relabels):
        ...
    
    def get_group_by_cols(self, alias=...):
        ...
    
    def as_sql(self, compiler, connection):
        ...
    
    def as_oracle(self, compiler, connection):
        ...
    
    @cached_property
    def contains_aggregate(self):
        ...
    
    @cached_property
    def contains_over_clause(self):
        ...
    
    @property
    def is_summary(self):
        ...
    
    @property
    def identity(self):
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    


class Transform(RegisterLookupMixin, Func):
    """
    RegisterLookupMixin() is first so that get_lookup() and get_transform()
    first examine self and then check output_field.
    """
    bilateral = ...
    arity = ...
    @property
    def lhs(self):
        ...
    
    def get_bilateral_transforms(self):
        ...
    


class BuiltinLookup(Lookup):
    def process_lhs(self, compiler, connection, lhs=...):
        ...
    
    def as_sql(self, compiler, connection):
        ...
    
    def get_rhs_op(self, connection, rhs):
        ...
    


class FieldGetDbPrepValueMixin:
    """
    Some lookups require Field.get_db_prep_value() to be called on their
    inputs.
    """
    get_db_prep_lookup_value_is_iterable = ...
    def get_db_prep_lookup(self, value, connection):
        ...
    


class FieldGetDbPrepValueIterableMixin(FieldGetDbPrepValueMixin):
    """
    Some lookups require Field.get_db_prep_value() to be called on each value
    in an iterable.
    """
    get_db_prep_lookup_value_is_iterable = ...
    def get_prep_lookup(self):
        ...
    
    def process_rhs(self, compiler, connection):
        ...
    
    def resolve_expression_parameter(self, compiler, connection, sql, param):
        ...
    
    def batch_process_rhs(self, compiler, connection, rhs=...):
        ...
    


class PostgresOperatorLookup(FieldGetDbPrepValueMixin, Lookup):
    """Lookup defined by operators on PostgreSQL."""
    postgres_operator = ...
    def as_postgresql(self, compiler, connection):
        ...
    


@Field.register_lookup
class Exact(FieldGetDbPrepValueMixin, BuiltinLookup):
    lookup_name = ...
    def process_rhs(self, compiler, connection):
        ...
    
    def as_sql(self, compiler, connection):
        ...
    


@Field.register_lookup
class IExact(BuiltinLookup):
    lookup_name = ...
    prepare_rhs = ...
    def process_rhs(self, qn, connection):
        ...
    


@Field.register_lookup
class GreaterThan(FieldGetDbPrepValueMixin, BuiltinLookup):
    lookup_name = ...


@Field.register_lookup
class GreaterThanOrEqual(FieldGetDbPrepValueMixin, BuiltinLookup):
    lookup_name = ...


@Field.register_lookup
class LessThan(FieldGetDbPrepValueMixin, BuiltinLookup):
    lookup_name = ...


@Field.register_lookup
class LessThanOrEqual(FieldGetDbPrepValueMixin, BuiltinLookup):
    lookup_name = ...


class IntegerFieldFloatRounding:
    """
    Allow floats to work as query values for IntegerField. Without this, the
    decimal portion of the float would always be discarded.
    """
    def get_prep_lookup(self):
        ...
    


@IntegerField.register_lookup
class IntegerGreaterThanOrEqual(IntegerFieldFloatRounding, GreaterThanOrEqual):
    ...


@IntegerField.register_lookup
class IntegerLessThan(IntegerFieldFloatRounding, LessThan):
    ...


@Field.register_lookup
class In(FieldGetDbPrepValueIterableMixin, BuiltinLookup):
    lookup_name = ...
    def process_rhs(self, compiler, connection):
        ...
    
    def get_rhs_op(self, connection, rhs):
        ...
    
    def as_sql(self, compiler, connection):
        ...
    
    def split_parameter_list_as_sql(self, compiler, connection):
        ...
    


class PatternLookup(BuiltinLookup):
    param_pattern = ...
    prepare_rhs = ...
    def get_rhs_op(self, connection, rhs):
        ...
    
    def process_rhs(self, qn, connection):
        ...
    


@Field.register_lookup
class Contains(PatternLookup):
    lookup_name = ...


@Field.register_lookup
class IContains(Contains):
    lookup_name = ...


@Field.register_lookup
class StartsWith(PatternLookup):
    lookup_name = ...
    param_pattern = ...


@Field.register_lookup
class IStartsWith(StartsWith):
    lookup_name = ...


@Field.register_lookup
class EndsWith(PatternLookup):
    lookup_name = ...
    param_pattern = ...


@Field.register_lookup
class IEndsWith(EndsWith):
    lookup_name = ...


@Field.register_lookup
class Range(FieldGetDbPrepValueIterableMixin, BuiltinLookup):
    lookup_name = ...
    def get_rhs_op(self, connection, rhs):
        ...
    


@Field.register_lookup
class IsNull(BuiltinLookup):
    lookup_name = ...
    prepare_rhs = ...
    def as_sql(self, compiler, connection):
        ...
    


@Field.register_lookup
class Regex(BuiltinLookup):
    lookup_name = ...
    prepare_rhs = ...
    def as_sql(self, compiler, connection):
        ...
    


@Field.register_lookup
class IRegex(Regex):
    lookup_name = ...


class YearLookup(Lookup):
    def year_lookup_bounds(self, connection, year):
        ...
    
    def as_sql(self, compiler, connection):
        ...
    
    def get_direct_rhs_sql(self, connection, rhs):
        ...
    
    def get_bound_params(self, start, finish):
        ...
    


class YearExact(YearLookup, Exact):
    def get_direct_rhs_sql(self, connection, rhs):
        ...
    
    def get_bound_params(self, start, finish):
        ...
    


class YearGt(YearLookup, GreaterThan):
    def get_bound_params(self, start, finish):
        ...
    


class YearGte(YearLookup, GreaterThanOrEqual):
    def get_bound_params(self, start, finish):
        ...
    


class YearLt(YearLookup, LessThan):
    def get_bound_params(self, start, finish):
        ...
    


class YearLte(YearLookup, LessThanOrEqual):
    def get_bound_params(self, start, finish):
        ...
    


class UUIDTextMixin:
    """
    Strip hyphens from a value when filtering a UUIDField on backends without
    a native datatype for UUID.
    """
    def process_rhs(self, qn, connection):
        ...
    


@UUIDField.register_lookup
class UUIDIExact(UUIDTextMixin, IExact):
    ...


@UUIDField.register_lookup
class UUIDContains(UUIDTextMixin, Contains):
    ...


@UUIDField.register_lookup
class UUIDIContains(UUIDTextMixin, IContains):
    ...


@UUIDField.register_lookup
class UUIDStartsWith(UUIDTextMixin, StartsWith):
    ...


@UUIDField.register_lookup
class UUIDIStartsWith(UUIDTextMixin, IStartsWith):
    ...


@UUIDField.register_lookup
class UUIDEndsWith(UUIDTextMixin, EndsWith):
    ...


@UUIDField.register_lookup
class UUIDIEndsWith(UUIDTextMixin, IEndsWith):
    ...


