from .main_loop import EventLoop as EventLoop, ExitMainLoop as ExitMainLoop

class TrioEventLoop(EventLoop):
    def __init__(self) -> None: ...
    def alarm(self, seconds, callback): ...
    def enter_idle(self, callback): ...
    def remove_alarm(self, handle): ...
    def remove_enter_idle(self, handle): ...
    def remove_watch_file(self, handle): ...
    def run(self) -> None: ...
    async def run_async(self) -> None: ...
    def watch_file(self, fd, callback): ...
