from typing import Any

REDRAW_SCREEN: str
CURSOR_UP: str
CURSOR_DOWN: str
CURSOR_LEFT: str
CURSOR_RIGHT: str
CURSOR_PAGE_UP: str
CURSOR_PAGE_DOWN: str
CURSOR_MAX_LEFT: str
CURSOR_MAX_RIGHT: str
ACTIVATE: str

class CommandMap:
    def __init__(self) -> None: ...
    def restore_defaults(self) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, command) -> None: ...
    def __delitem__(self, key) -> None: ...
    def clear_command(self, command) -> None: ...
    def copy(self): ...

command_map: Any
