from typing import Any
from urwid import util as util
from urwid.display_common import AttrSpec as AttrSpec, BaseScreen as BaseScreen
from urwid.main_loop import ExitMainLoop as ExitMainLoop

class HtmlGeneratorSimulationError(Exception): ...

class HtmlGenerator(BaseScreen):
    fragments: Any
    sizes: Any
    keys: Any
    started: bool
    colors: int
    bright_is_bold: bool
    has_underline: bool
    def __init__(self) -> None: ...
    def set_terminal_properties(self, colors: Any | None = ..., bright_is_bold: Any | None = ..., has_underline: Any | None = ...) -> None: ...
    def set_mouse_tracking(self, enable: bool = ...) -> None: ...
    def set_input_timeouts(self, *args) -> None: ...
    def reset_default_terminal_palette(self, *args) -> None: ...
    def draw_screen(self, size, r) -> None: ...
    def clear(self) -> None: ...
    def get_cols_rows(self): ...
    def get_input(self, raw_keys: bool = ...): ...

def html_span(s, aspec, cursor: int = ...): ...
def html_escape(text): ...
def screenshot_init(sizes, keys) -> None: ...
def screenshot_collect(): ...
