from typing import Any
from urwid.compat import PYTHON3 as PYTHON3, xrange as xrange

class MonitoredList(list):
    def set_modified_callback(self, callback) -> None: ...
    __add__: Any
    __delitem__: Any
    __delslice__: Any
    __iadd__: Any
    __imul__: Any
    __rmul__: Any
    __setitem__: Any
    __setslice__: Any
    append: Any
    extend: Any
    insert: Any
    pop: Any
    remove: Any
    reverse: Any
    sort: Any
    clear: Any

class MonitoredFocusList(MonitoredList):
    def __init__(self, *argl, **argd) -> None: ...
    focus: Any
    def set_focus_changed_callback(self, callback) -> None: ...
    def set_validate_contents_modified(self, callback) -> None: ...
    def __delitem__(self, y): ...
    def __setitem__(self, i, y): ...
    def __delslice__(self, i, j): ...
    def __setslice__(self, i, j, y): ...
    def __imul__(self, n): ...
    def append(self, item): ...
    def extend(self, items): ...
    def insert(self, index, item): ...
    def pop(self, index: int = ...): ...
    def remove(self, value): ...
    def reverse(self): ...
    def sort(self, **kwargs): ...
    def clear(self): ...
