from typing import Any
from urwid import Edit as Edit

class NumEdit(Edit):
    ALLOWED: str
    trimLeadingZeros: Any
    def __init__(self, allowed, caption, default, trimLeadingZeros: bool = ...) -> None: ...
    def valid_char(self, ch): ...
    def keypress(self, size, key): ...

class IntegerEdit(NumEdit):
    base: Any
    def __init__(self, caption: str = ..., default: Any | None = ..., base: int = ...) -> None: ...
    def value(self): ...

class FloatEdit(NumEdit):
    significance: Any
    def __init__(self, caption: str = ..., default: Any | None = ..., preserveSignificance: bool = ..., decimalSeparator: str = ...) -> None: ...
    def value(self): ...
