from typing import Any
from urwid.compat import B as B, bytes as bytes, ord2 as ord2, text_type as text_type

SAFE_ASCII_RE: Any
SAFE_ASCII_BYTES_RE: Any
widths: Any

def get_width(o): ...
def decode_one(text, pos): ...
def decode_one_uni(text, i): ...
def decode_one_right(text, pos): ...
def set_byte_encoding(enc) -> None: ...
def get_byte_encoding(): ...
def calc_text_pos(text, start_offs, end_offs, pref_col): ...
def calc_width(text, start_offs, end_offs): ...
def is_wide_char(text, offs): ...
def move_prev_char(text, start_offs, end_offs): ...
def move_next_char(text, start_offs, end_offs): ...
def within_double_byte(text, line_start, pos): ...
def process_east_asian_width() -> None: ...
