"""
This type stub file was generated by pyright.
"""

"""Utility module to parse a Feedback buffer"""
def parseFeedback(buffer, entryCount):
    """Parse the feedback buffer into Python object records"""
    ...

SINGLE_VERTEX_TOKENS = ...
DOUBLE_VERTEX_TOKENS = ...
class Vertex(object):
    """Simplistic holder for vertex data from a feedback buffer"""
    __slots__ = ...
    def __init__(self, vertex, color=..., texture=...) -> None:
        """Store values for access"""
        ...
    


def createGetVertex():
    ...

