"""
This type stub file was generated by pyright.
"""

from OpenGL import GL
from OpenGL.GL.ARB import shader_objects
from OpenGL.extensions import alternate

"""Convenience module providing common shader entry points

The point of this module is to allow client code to use
OpenGL Core names to reference shader-related operations
even if the local hardware only supports ARB extension-based
shader rendering.

There are also two utility methods compileProgram and compileShader
which make it easy to create demos which are shader-using.
"""
log = ...
_excludes = ...
glAttachShader = alternate(GL.glAttachShader, shader_objects.glAttachObjectARB)
glDetachShader = alternate(GL.glDetachShader, shader_objects.glDetachObjectARB)
glDeleteShader = alternate(GL.glDeleteShader, shader_objects.glDeleteObjectARB)
glGetAttachedShaders = alternate(GL.glGetAttachedShaders, shader_objects.glGetAttachedObjectsARB)
glGetProgramInfoLog = alternate(GL.glGetProgramInfoLog, shader_objects.glGetInfoLogARB)
glGetShaderInfoLog = alternate(GL.glGetShaderInfoLog, shader_objects.glGetInfoLogARB)
glGetShaderiv = alternate(GL.glGetShaderiv, shader_objects.glGetObjectParameterivARB)
glGetProgramiv = alternate(GL.glGetProgramiv, shader_objects.glGetObjectParameterivARB)
GL_VALIDATE_STATUS = ...
GL_COMPILE_STATUS = ...
GL_LINK_STATUS = ...
GL_FALSE = ...
GL_TRUE = ...
class ShaderProgram(int):
    """Integer sub-class with context-manager operation"""
    validated = ...
    def __enter__(self):
        """Start use of the program"""
        ...
    
    def __exit__(self, typ, val, tb):
        """Stop use of the program"""
        ...
    
    def check_validate(self):
        """Check that the program validates
        
        Validation has to occur *after* linking/loading
        
        raises ShaderValidationError on failures
        """
        ...
    
    def check_linked(self):
        """Check link status for this program
        
        raises ShaderLinkError on failures
        """
        ...
    
    def retrieve(self):
        """Attempt to retrieve binary for this compiled shader
        
        Note that binaries for a program are *not* generally portable,
        they should be used solely for caching compiled programs for 
        local use; i.e. to reduce compilation overhead.
        
        returns (format,binaryData) for the shader program
        """
        ...
    
    def load(self, format, binary, validate=...):
        """Attempt to load binary-format for a pre-compiled shader
        
        See notes in retrieve
        """
        ...
    


def compileProgram(*shaders, **named):
    """Create a new program, attach shaders and validate

    shaders -- arbitrary number of shaders to attach to the
        generated program.
    separable (keyword only) -- set the separable flag to allow 
        for partial installation of shader into the pipeline (see 
        glUseProgramStages)
    retrievable (keyword only) -- set the retrievable flag to 
        allow retrieval of the program binary representation, (see 
        glProgramBinary, glGetProgramBinary)
    validate (keyword only) -- if False, suppress automatic 
        validation against current GL state. In advanced usage 
        the validation can produce spurious errors. Note: this 
        function is *not* really intended for advanced usage,
        if you're finding yourself specifying this flag you 
        likely should be using your own shader management code.

    This convenience function is *not* standard OpenGL,
    but it does wind up being fairly useful for demos
    and the like.  You may wish to copy it to your code
    base to guard against PyOpenGL changes.

    Usage:

        shader = compileProgram(
            compileShader( source, GL_VERTEX_SHADER ),
            compileShader( source2, GL_FRAGMENT_SHADER ),
        )
        glUseProgram( shader )

    Note:
        If (and only if) validation of the linked program
        *passes* then the passed-in shader objects will be
        deleted from the GL.

    returns ShaderProgram() (GLuint) program reference
    raises RuntimeError subclasses {
        ShaderCompilationError, ShaderValidationError, ShaderLinkError,
    } when a link/validation failure occurs
    """
    ...

def compileShader(source, shaderType):
    """Compile shader source of given type

    source -- GLSL source-code for the shader
    shaderType -- GLenum GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, etc,

    returns GLuint compiled shader reference
    raises RuntimeError when a compilation failure occurs
    """
    ...

class ShaderCompilationError(RuntimeError):
    """Raised when a shader compilation fails"""
    ...


class ShaderValidationError(RuntimeError):
    """Raised when a program fails to validate"""
    ...


class ShaderLinkError(RuntimeError):
    """Raised when a shader link fails"""
    ...


