"""
This type stub file was generated by pyright.
"""

from OpenGL.arrays import vbo

class Implementation(vbo.Implementation):
    """OpenGL-based implementation of VBO interfaces"""
    def __init__(self) -> None:
        ...
    


