"""
This type stub file was generated by pyright.
"""

from OpenGL import arrays, platform as _p
from OpenGL.raw.GL import _types as _cs
from OpenGL.raw.GL._types import *

'''Autogenerated by xml_generate script, do not edit!'''
_EXTENSION_NAME = ...
GL_ANY_SAMPLES_PASSED = ...
GL_INT_2_10_10_10_REV = ...
GL_MAX_DUAL_SOURCE_DRAW_BUFFERS = ...
GL_ONE_MINUS_SRC1_ALPHA = ...
GL_ONE_MINUS_SRC1_COLOR = ...
GL_RGB10_A2UI = ...
GL_SAMPLER_BINDING = ...
GL_SRC1_COLOR = ...
GL_TEXTURE_SWIZZLE_A = ...
GL_TEXTURE_SWIZZLE_B = ...
GL_TEXTURE_SWIZZLE_G = ...
GL_TEXTURE_SWIZZLE_R = ...
GL_TEXTURE_SWIZZLE_RGBA = ...
GL_TIMESTAMP = ...
GL_TIME_ELAPSED = ...
GL_VERTEX_ATTRIB_ARRAY_DIVISOR = ...
@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLuint, arrays.GLcharArray)
def glBindFragDataLocationIndexed(program, colorNumber, index, name):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint)
def glBindSampler(unit, sampler):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLuint)
def glColorP3ui(type, color):
    ...

@_f
@_p.types(None, _cs.GLenum, arrays.GLuintArray)
def glColorP3uiv(type, color):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLuint)
def glColorP4ui(type, color):
    ...

@_f
@_p.types(None, _cs.GLenum, arrays.GLuintArray)
def glColorP4uiv(type, color):
    ...

@_f
@_p.types(None, _cs.GLsizei, arrays.GLuintArray)
def glDeleteSamplers(count, samplers):
    ...

@_f
@_p.types(None, _cs.GLsizei, arrays.GLuintArray)
def glGenSamplers(count, samplers):
    ...

@_f
@_p.types(_cs.GLint, _cs.GLuint, arrays.GLcharArray)
def glGetFragDataIndex(program, name):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLint64Array)
def glGetQueryObjecti64v(id, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLuint64Array)
def glGetQueryObjectui64v(id, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLintArray)
def glGetSamplerParameterIiv(sampler, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLuintArray)
def glGetSamplerParameterIuiv(sampler, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLfloatArray)
def glGetSamplerParameterfv(sampler, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLintArray)
def glGetSamplerParameteriv(sampler, pname, params):
    ...

@_f
@_p.types(_cs.GLboolean, _cs.GLuint)
def glIsSampler(sampler):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLenum, _cs.GLuint)
def glMultiTexCoordP1ui(texture, type, coords):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLenum, arrays.GLuintArray)
def glMultiTexCoordP1uiv(texture, type, coords):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLenum, _cs.GLuint)
def glMultiTexCoordP2ui(texture, type, coords):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLenum, arrays.GLuintArray)
def glMultiTexCoordP2uiv(texture, type, coords):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLenum, _cs.GLuint)
def glMultiTexCoordP3ui(texture, type, coords):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLenum, arrays.GLuintArray)
def glMultiTexCoordP3uiv(texture, type, coords):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLenum, _cs.GLuint)
def glMultiTexCoordP4ui(texture, type, coords):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLenum, arrays.GLuintArray)
def glMultiTexCoordP4uiv(texture, type, coords):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLuint)
def glNormalP3ui(type, coords):
    ...

@_f
@_p.types(None, _cs.GLenum, arrays.GLuintArray)
def glNormalP3uiv(type, coords):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum)
def glQueryCounter(id, target):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLintArray)
def glSamplerParameterIiv(sampler, pname, param):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLuintArray)
def glSamplerParameterIuiv(sampler, pname, param):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLfloat)
def glSamplerParameterf(sampler, pname, param):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLfloatArray)
def glSamplerParameterfv(sampler, pname, param):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLint)
def glSamplerParameteri(sampler, pname, param):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLintArray)
def glSamplerParameteriv(sampler, pname, param):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLuint)
def glSecondaryColorP3ui(type, color):
    ...

@_f
@_p.types(None, _cs.GLenum, arrays.GLuintArray)
def glSecondaryColorP3uiv(type, color):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLuint)
def glTexCoordP1ui(type, coords):
    ...

@_f
@_p.types(None, _cs.GLenum, arrays.GLuintArray)
def glTexCoordP1uiv(type, coords):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLuint)
def glTexCoordP2ui(type, coords):
    ...

@_f
@_p.types(None, _cs.GLenum, arrays.GLuintArray)
def glTexCoordP2uiv(type, coords):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLuint)
def glTexCoordP3ui(type, coords):
    ...

@_f
@_p.types(None, _cs.GLenum, arrays.GLuintArray)
def glTexCoordP3uiv(type, coords):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLuint)
def glTexCoordP4ui(type, coords):
    ...

@_f
@_p.types(None, _cs.GLenum, arrays.GLuintArray)
def glTexCoordP4uiv(type, coords):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint)
def glVertexAttribDivisor(index, divisor):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLboolean, _cs.GLuint)
def glVertexAttribP1ui(index, type, normalized, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLboolean, arrays.GLuintArray)
def glVertexAttribP1uiv(index, type, normalized, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLboolean, _cs.GLuint)
def glVertexAttribP2ui(index, type, normalized, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLboolean, arrays.GLuintArray)
def glVertexAttribP2uiv(index, type, normalized, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLboolean, _cs.GLuint)
def glVertexAttribP3ui(index, type, normalized, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLboolean, arrays.GLuintArray)
def glVertexAttribP3uiv(index, type, normalized, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLboolean, _cs.GLuint)
def glVertexAttribP4ui(index, type, normalized, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLboolean, arrays.GLuintArray)
def glVertexAttribP4uiv(index, type, normalized, value):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLuint)
def glVertexP2ui(type, value):
    ...

@_f
@_p.types(None, _cs.GLenum, arrays.GLuintArray)
def glVertexP2uiv(type, value):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLuint)
def glVertexP3ui(type, value):
    ...

@_f
@_p.types(None, _cs.GLenum, arrays.GLuintArray)
def glVertexP3uiv(type, value):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLuint)
def glVertexP4ui(type, value):
    ...

@_f
@_p.types(None, _cs.GLenum, arrays.GLuintArray)
def glVertexP4uiv(type, value):
    ...

