"""
This type stub file was generated by pyright.
"""

from OpenGL import arrays, platform as _p
from OpenGL.raw.GLX import _types as _cs
from OpenGL.raw.GLX._types import *

'''Autogenerated by xml_generate script, do not edit!'''
_EXTENSION_NAME = ...
GLX_SAMPLES = ...
GLX_SAMPLE_BUFFERS = ...
@_f
@_p.types(_cs.__GLXextFuncPtr, arrays.GLubyteArray)
def glXGetProcAddress(procName):
    ...

