"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GLX.VERSION.GLX_1_3 import *

"""
This type stub file was generated by pyright.
"""
def glInitGlx13VERSION():
    '''Return boolean indicating whether this extension is available'''
    ...

