"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GLX.VERSION.GLX_1_0 import *

"""
This type stub file was generated by pyright.
"""
def glInitGlx10VERSION():
    '''Return boolean indicating whether this extension is available'''
    ...

