"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GLX.VERSION.GLX_1_1 import *

"""
This type stub file was generated by pyright.
"""
def glInitGlx11VERSION():
    '''Return boolean indicating whether this extension is available'''
    ...

