"""
This type stub file was generated by pyright.
"""

from typing import Any

"""
This type stub file was generated by pyright.
"""
_NBitByte = Any
_NBitShort = Any
_NBitIntC = Any
_NBitIntP = Any
_NBitInt = Any
_NBitLongLong = Any
_NBitHalf = Any
_NBitSingle = Any
_NBitDouble = Any
_NBitLongDouble = Any
