"""
This type stub file was generated by pyright.
"""

import ctypes
from OpenGL import arrays, platform as _p
from OpenGL.raw.GLES2 import _types as _cs
from OpenGL.raw.GLES2._types import *

'''Autogenerated by xml_generate script, do not edit!'''
_EXTENSION_NAME = ...
GL_BUFFER_ACCESS_OES = ...
GL_BUFFER_MAPPED_OES = ...
GL_BUFFER_MAP_POINTER_OES = ...
GL_WRITE_ONLY_OES = ...
@_f
@_p.types(None, _cs.GLenum, _cs.GLenum, arrays.GLvoidpArray)
def glGetBufferPointervOES(target, pname, params):
    ...

@_f
@_p.types(ctypes.c_void_p, _cs.GLenum, _cs.GLenum)
def glMapBufferOES(target, access):
    ...

@_f
@_p.types(_cs.GLboolean, _cs.GLenum)
def glUnmapBufferOES(target):
    ...

