"""
This type stub file was generated by pyright.
"""

from html.parser import HTMLParser

"""Compare two HTML documents."""
ASCII_WHITESPACE = ...
def normalize_whitespace(string):
    ...

class Element:
    def __init__(self, name, attributes) -> None:
        ...
    
    def append(self, element):
        ...
    
    def finalize(self):
        ...
    
    def __eq__(self, element) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __contains__(self, element):
        ...
    
    def count(self, element):
        ...
    
    def __getitem__(self, key):
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self):
        ...
    


class RootElement(Element):
    def __init__(self) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class HTMLParseError(Exception):
    ...


class Parser(HTMLParser):
    SELF_CLOSING_TAGS = ...
    def __init__(self) -> None:
        ...
    
    def error(self, msg):
        ...
    
    def format_position(self, position=..., element=...):
        ...
    
    @property
    def current(self):
        ...
    
    def handle_startendtag(self, tag, attrs):
        ...
    
    def handle_starttag(self, tag, attrs):
        ...
    
    def handle_endtag(self, tag):
        ...
    
    def handle_data(self, data):
        ...
    


def parse_html(html):
    """
    Take a string that contains HTML and turn it into a Python object structure
    that can be easily compared against other HTML on semantic equivalence.
    Syntactical differences like which quotation is used on arguments will be
    ignored.
    """
    ...

