"""
This type stub file was generated by pyright.
"""

from django.core.signals import setting_changed
from django.dispatch import receiver

template_rendered = ...
COMPLEX_OVERRIDE_SETTINGS = ...
@receiver(setting_changed)
def clear_cache_handlers(**kwargs):
    ...

@receiver(setting_changed)
def update_installed_apps(**kwargs):
    ...

@receiver(setting_changed)
def update_connections_time_zone(**kwargs):
    ...

@receiver(setting_changed)
def clear_routers_cache(**kwargs):
    ...

@receiver(setting_changed)
def reset_template_engines(**kwargs):
    ...

@receiver(setting_changed)
def clear_serializers_cache(**kwargs):
    ...

@receiver(setting_changed)
def language_changed(**kwargs):
    ...

@receiver(setting_changed)
def localize_settings_changed(**kwargs):
    ...

@receiver(setting_changed)
def file_storage_changed(**kwargs):
    ...

@receiver(setting_changed)
def complex_setting_changed(**kwargs):
    ...

@receiver(setting_changed)
def root_urlconf_changed(**kwargs):
    ...

@receiver(setting_changed)
def static_storage_changed(**kwargs):
    ...

@receiver(setting_changed)
def static_finders_changed(**kwargs):
    ...

@receiver(setting_changed)
def auth_password_validators_changed(**kwargs):
    ...

@receiver(setting_changed)
def user_model_swapped(**kwargs):
    ...

