"""
This type stub file was generated by pyright.
"""

NOT_PROVIDED = ...
class FieldCacheMixin:
    """Provide an API for working with the model's fields value cache."""
    def get_cache_name(self):
        ...
    
    def get_cached_value(self, instance, default=...):
        ...
    
    def is_cached(self, instance):
        ...
    
    def set_cached_value(self, instance, value):
        ...
    
    def delete_cached_value(self, instance):
        ...
    


class CheckFieldDefaultMixin:
    _default_hint = ...
    def check(self, **kwargs):
        ...
    


