"""
This type stub file was generated by pyright.
"""

from OpenGL import lazywrapper as _lazywrapper
from OpenGL.raw.GL.ARB.ES2_compatibility import *

'''OpenGL extension ARB.ES2_compatibility

This module customises the behaviour of the 
OpenGL.raw.GL.ARB.ES2_compatibility to provide a more 
Python-friendly API

Overview (from the spec)
	
	This extension adds support for features of OpenGL ES 2.0 that are
	missing from OpenGL 3.x. Enabling these features will ease the process
	of porting applications from OpenGL ES 2.0 to OpenGL.

The official definition of this extension is available here:
http://www.opengl.org/registry/specs/ARB/ES2_compatibility.txt
'''
def glInitEs2CompatibilityARB():
    '''Return boolean indicating whether this extension is available'''
    ...

glShaderBinary = ...
glGetShaderPrecisionFormat = ...
@_lazywrapper.lazy(glGetShaderPrecisionFormat)
def glGetShaderPrecisionFormat(baseOperation, shadertype, precisiontype, range=..., precision=...):
    """Provides range and precision if not provided, returns (range,precision)"""
    ...

