"""
This type stub file was generated by pyright.
"""

from typing import Any, List

"""
This type stub file was generated by pyright.
"""
__all__: List[str]
matrix: Any
bmat: Any
mat: Any
asmatrix: Any
