"""
This type stub file was generated by pyright.
"""

from django.core.cache.backends.base import BaseCache

"File-based cache backend"
class FileBasedCache(BaseCache):
    cache_suffix = ...
    pickle_protocol = ...
    def __init__(self, dir, params) -> None:
        ...
    
    def add(self, key, value, timeout=..., version=...):
        ...
    
    def get(self, key, default=..., version=...):
        ...
    
    def set(self, key, value, timeout=..., version=...):
        ...
    
    def touch(self, key, timeout=..., version=...):
        ...
    
    def delete(self, key, version=...):
        ...
    
    def has_key(self, key, version=...):
        ...
    
    def clear(self):
        """
        Remove all the cache files.
        """
        ...
    


