"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.VERSION.GL_4_6 import *

"""
This type stub file was generated by pyright.
"""
def glInitGl46VERSION():
    '''Return boolean indicating whether this extension is available'''
    ...

