"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.VERSION.GL_4_2 import *
from OpenGL.GL.ARB.base_instance import *
from OpenGL.GL.ARB.shading_language_420pack import *
from OpenGL.GL.ARB.transform_feedback_instanced import *
from OpenGL.GL.ARB.compressed_texture_pixel_storage import *
from OpenGL.GL.ARB.conservative_depth import *
from OpenGL.GL.ARB.internalformat_query import *
from OpenGL.GL.ARB.map_buffer_alignment import *
from OpenGL.GL.ARB.shader_atomic_counters import *
from OpenGL.GL.ARB.shader_image_load_store import *
from OpenGL.GL.ARB.shading_language_packing import *
from OpenGL.GL.ARB.texture_storage import *

"""
This type stub file was generated by pyright.
"""
def glInitGl42VERSION():
    '''Return boolean indicating whether this extension is available'''
    ...

glDrawElementsInstancedBaseInstance = ...
glDrawElementsInstancedBaseVertexBaseInstance = ...
glGetInternalformativ = ...
glGetActiveAtomicCounterBufferiv = ...
