"""
This type stub file was generated by pyright.
"""

from OpenGL import platform as _p
from OpenGL.raw.GL import _types as _cs
from OpenGL.raw.GL._types import *

"""
This type stub file was generated by pyright.
"""
_EXTENSION_NAME = ...
GL_DRAW_FRAMEBUFFER_BINDING_EXT = ...
GL_DRAW_FRAMEBUFFER_EXT = ...
GL_READ_FRAMEBUFFER_BINDING_EXT = ...
GL_READ_FRAMEBUFFER_EXT = ...
@_f
@_p.types(None, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLbitfield, _cs.GLenum)
def glBlitFramebufferEXT(srcX0, srcY0, srcX1, srcY1, dstX0, dstY0, dstX1, dstY1, mask, filter):
    ...

