"""
This type stub file was generated by pyright.
"""

import ctypes
from OpenGL import platform as _p
from OpenGL.raw.GLX import _types as _cs
from OpenGL.raw.GLX._types import *

'''Autogenerated by xml_generate script, do not edit!'''
_EXTENSION_NAME = ...
@_f
@_p.types(ctypes.POINTER(_cs.Display))
def glXGetCurrentDisplay():
    ...

