"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.VERSION.GL_2_1 import *

'''OpenGL extension VERSION.GL_2_1

This module customises the behaviour of the 
OpenGL.raw.GL.VERSION.GL_2_1 to provide a more 
Python-friendly API

The official definition of this extension is available here:
http://www.opengl.org/registry/specs/VERSION/GL_2_1.txt
'''
def glInitGl21VERSION():
    '''Return boolean indicating whether this extension is available'''
    ...

glUniformMatrix2x3fv = ...
glUniformMatrix3x2fv = ...
glUniformMatrix2x4fv = ...
glUniformMatrix4x2fv = ...
glUniformMatrix3x4fv = ...
glUniformMatrix4x3fv = ...
