"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL.VERSION.GL_4_6 import *

'''OpenGL extension VERSION.GL_4_6

This module customises the behaviour of the 
OpenGL.raw.GL.VERSION.GL_4_6 to provide a more 
Python-friendly API

The official definition of this extension is available here:
http://www.opengl.org/registry/specs/VERSION/GL_4_6.txt
'''
def glInitGl46VERSION():
    '''Return boolean indicating whether this extension is available'''
    ...

