"""
This type stub file was generated by pyright.
"""

import ctypes
from OpenGL import arrays, platform as _p
from OpenGL.raw.GL import _types as _cs
from OpenGL.raw.GL._types import *

"""
This type stub file was generated by pyright.
"""
_EXTENSION_NAME = ...
GL_BACK = ...
GL_CLIP_DEPTH_MODE = ...
GL_CLIP_ORIGIN = ...
GL_CONTEXT_FLAG_ROBUST_ACCESS_BIT = ...
GL_CONTEXT_LOST = ...
GL_CONTEXT_LOST = ...
GL_CONTEXT_RELEASE_BEHAVIOR = ...
GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH = ...
GL_GUILTY_CONTEXT_RESET = ...
GL_INNOCENT_CONTEXT_RESET = ...
GL_LOSE_CONTEXT_ON_RESET = ...
GL_LOWER_LEFT = ...
GL_MAX_COMBINED_CLIP_AND_CULL_DISTANCES = ...
GL_MAX_CULL_DISTANCES = ...
GL_NEGATIVE_ONE_TO_ONE = ...
GL_NONE = ...
GL_NO_ERROR = ...
GL_NO_RESET_NOTIFICATION = ...
GL_QUERY_BY_REGION_NO_WAIT_INVERTED = ...
GL_QUERY_BY_REGION_WAIT_INVERTED = ...
GL_QUERY_NO_WAIT_INVERTED = ...
GL_QUERY_TARGET = ...
GL_QUERY_WAIT_INVERTED = ...
GL_RESET_NOTIFICATION_STRATEGY = ...
GL_TEXTURE_BINDING_1D = ...
GL_TEXTURE_BINDING_1D_ARRAY = ...
GL_TEXTURE_BINDING_2D = ...
GL_TEXTURE_BINDING_2D_ARRAY = ...
GL_TEXTURE_BINDING_2D_MULTISAMPLE = ...
GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY = ...
GL_TEXTURE_BINDING_3D = ...
GL_TEXTURE_BINDING_BUFFER = ...
GL_TEXTURE_BINDING_CUBE_MAP = ...
GL_TEXTURE_BINDING_CUBE_MAP_ARRAY = ...
GL_TEXTURE_BINDING_RECTANGLE = ...
GL_TEXTURE_TARGET = ...
GL_UNKNOWN_CONTEXT_RESET = ...
GL_UPPER_LEFT = ...
GL_ZERO_TO_ONE = ...
@_f
@_p.types(None, _cs.GLuint, _cs.GLuint)
def glBindTextureUnit(unit, texture):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLbitfield, _cs.GLenum)
def glBlitNamedFramebuffer(readFramebuffer, drawFramebuffer, srcX0, srcY0, srcX1, srcY1, dstX0, dstY0, dstX1, dstY1, mask, filter):
    ...

@_f
@_p.types(_cs.GLenum, _cs.GLuint, _cs.GLenum)
def glCheckNamedFramebufferStatus(framebuffer, target):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLenum, _cs.GLenum, ctypes.c_void_p)
def glClearNamedBufferData(buffer, internalformat, format, type, data):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLintptr, _cs.GLsizeiptr, _cs.GLenum, _cs.GLenum, ctypes.c_void_p)
def glClearNamedBufferSubData(buffer, internalformat, offset, size, format, type, data):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLint, _cs.GLfloat, _cs.GLint)
def glClearNamedFramebufferfi(framebuffer, buffer, drawbuffer, depth, stencil):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLint, arrays.GLfloatArray)
def glClearNamedFramebufferfv(framebuffer, buffer, drawbuffer, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLint, arrays.GLintArray)
def glClearNamedFramebufferiv(framebuffer, buffer, drawbuffer, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLint, arrays.GLuintArray)
def glClearNamedFramebufferuiv(framebuffer, buffer, drawbuffer, value):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLenum)
def glClipControl(origin, depth):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLint, _cs.GLsizei, _cs.GLenum, _cs.GLsizei, ctypes.c_void_p)
def glCompressedTextureSubImage1D(texture, level, xoffset, width, format, imageSize, data):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLsizei, _cs.GLsizei, _cs.GLenum, _cs.GLsizei, ctypes.c_void_p)
def glCompressedTextureSubImage2D(texture, level, xoffset, yoffset, width, height, format, imageSize, data):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLsizei, _cs.GLsizei, _cs.GLsizei, _cs.GLenum, _cs.GLsizei, ctypes.c_void_p)
def glCompressedTextureSubImage3D(texture, level, xoffset, yoffset, zoffset, width, height, depth, format, imageSize, data):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLintptr, _cs.GLintptr, _cs.GLsizeiptr)
def glCopyNamedBufferSubData(readBuffer, writeBuffer, readOffset, writeOffset, size):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLsizei)
def glCopyTextureSubImage1D(texture, level, xoffset, x, y, width):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLsizei, _cs.GLsizei)
def glCopyTextureSubImage2D(texture, level, xoffset, yoffset, x, y, width, height):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLsizei, _cs.GLsizei)
def glCopyTextureSubImage3D(texture, level, xoffset, yoffset, zoffset, x, y, width, height):
    ...

@_f
@_p.types(None, _cs.GLsizei, arrays.GLuintArray)
def glCreateBuffers(n, buffers):
    ...

@_f
@_p.types(None, _cs.GLsizei, arrays.GLuintArray)
def glCreateFramebuffers(n, framebuffers):
    ...

@_f
@_p.types(None, _cs.GLsizei, arrays.GLuintArray)
def glCreateProgramPipelines(n, pipelines):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLsizei, arrays.GLuintArray)
def glCreateQueries(target, n, ids):
    ...

@_f
@_p.types(None, _cs.GLsizei, arrays.GLuintArray)
def glCreateRenderbuffers(n, renderbuffers):
    ...

@_f
@_p.types(None, _cs.GLsizei, arrays.GLuintArray)
def glCreateSamplers(n, samplers):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLsizei, arrays.GLuintArray)
def glCreateTextures(target, n, textures):
    ...

@_f
@_p.types(None, _cs.GLsizei, arrays.GLuintArray)
def glCreateTransformFeedbacks(n, ids):
    ...

@_f
@_p.types(None, _cs.GLsizei, arrays.GLuintArray)
def glCreateVertexArrays(n, arrays):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint)
def glDisableVertexArrayAttrib(vaobj, index):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint)
def glEnableVertexArrayAttrib(vaobj, index):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLintptr, _cs.GLsizeiptr)
def glFlushMappedNamedBufferRange(buffer, offset, length):
    ...

@_f
@_p.types(None, _cs.GLuint)
def glGenerateTextureMipmap(texture):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, ctypes.c_void_p)
def glGetCompressedTextureImage(texture, level, bufSize, pixels):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLsizei, _cs.GLsizei, _cs.GLsizei, _cs.GLsizei, ctypes.c_void_p)
def glGetCompressedTextureSubImage(texture, level, xoffset, yoffset, zoffset, width, height, depth, bufSize, pixels):
    ...

@_f
@_p.types(_cs.GLenum)
def glGetGraphicsResetStatus():
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLint64Array)
def glGetNamedBufferParameteri64v(buffer, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLintArray)
def glGetNamedBufferParameteriv(buffer, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLvoidpArray)
def glGetNamedBufferPointerv(buffer, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLintptr, _cs.GLsizeiptr, ctypes.c_void_p)
def glGetNamedBufferSubData(buffer, offset, size, data):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLenum, arrays.GLintArray)
def glGetNamedFramebufferAttachmentParameteriv(framebuffer, attachment, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLintArray)
def glGetNamedFramebufferParameteriv(framebuffer, pname, param):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLintArray)
def glGetNamedRenderbufferParameteriv(renderbuffer, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLenum, _cs.GLintptr)
def glGetQueryBufferObjecti64v(id, buffer, pname, offset):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLenum, _cs.GLintptr)
def glGetQueryBufferObjectiv(id, buffer, pname, offset):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLenum, _cs.GLintptr)
def glGetQueryBufferObjectui64v(id, buffer, pname, offset):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLenum, _cs.GLintptr)
def glGetQueryBufferObjectuiv(id, buffer, pname, offset):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLenum, _cs.GLenum, _cs.GLsizei, ctypes.c_void_p)
def glGetTextureImage(texture, level, format, type, bufSize, pixels):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLenum, arrays.GLfloatArray)
def glGetTextureLevelParameterfv(texture, level, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLenum, arrays.GLintArray)
def glGetTextureLevelParameteriv(texture, level, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLintArray)
def glGetTextureParameterIiv(texture, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLuintArray)
def glGetTextureParameterIuiv(texture, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLfloatArray)
def glGetTextureParameterfv(texture, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLintArray)
def glGetTextureParameteriv(texture, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLsizei, _cs.GLsizei, _cs.GLsizei, _cs.GLenum, _cs.GLenum, _cs.GLsizei, ctypes.c_void_p)
def glGetTextureSubImage(texture, level, xoffset, yoffset, zoffset, width, height, depth, format, type, bufSize, pixels):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLuint, arrays.GLint64Array)
def glGetTransformFeedbacki64_v(xfb, pname, index, param):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLuint, arrays.GLintArray)
def glGetTransformFeedbacki_v(xfb, pname, index, param):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLintArray)
def glGetTransformFeedbackiv(xfb, pname, param):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLenum, arrays.GLint64Array)
def glGetVertexArrayIndexed64iv(vaobj, index, pname, param):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLenum, arrays.GLintArray)
def glGetVertexArrayIndexediv(vaobj, index, pname, param):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLintArray)
def glGetVertexArrayiv(vaobj, pname, param):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLenum, _cs.GLenum, _cs.GLsizei, ctypes.c_void_p)
def glGetnColorTable(target, format, type, bufSize, table):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLint, _cs.GLsizei, ctypes.c_void_p)
def glGetnCompressedTexImage(target, lod, bufSize, pixels):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLenum, _cs.GLenum, _cs.GLsizei, ctypes.c_void_p)
def glGetnConvolutionFilter(target, format, type, bufSize, image):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLboolean, _cs.GLenum, _cs.GLenum, _cs.GLsizei, ctypes.c_void_p)
def glGetnHistogram(target, reset, format, type, bufSize, values):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLenum, _cs.GLsizei, arrays.GLdoubleArray)
def glGetnMapdv(target, query, bufSize, v):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLenum, _cs.GLsizei, arrays.GLfloatArray)
def glGetnMapfv(target, query, bufSize, v):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLenum, _cs.GLsizei, arrays.GLintArray)
def glGetnMapiv(target, query, bufSize, v):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLboolean, _cs.GLenum, _cs.GLenum, _cs.GLsizei, ctypes.c_void_p)
def glGetnMinmax(target, reset, format, type, bufSize, values):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLsizei, arrays.GLfloatArray)
def glGetnPixelMapfv(map, bufSize, values):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLsizei, arrays.GLuintArray)
def glGetnPixelMapuiv(map, bufSize, values):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLsizei, arrays.GLushortArray)
def glGetnPixelMapusv(map, bufSize, values):
    ...

@_f
@_p.types(None, _cs.GLsizei, arrays.GLubyteArray)
def glGetnPolygonStipple(bufSize, pattern):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLenum, _cs.GLenum, _cs.GLsizei, ctypes.c_void_p, _cs.GLsizei, ctypes.c_void_p, ctypes.c_void_p)
def glGetnSeparableFilter(target, format, type, rowBufSize, row, columnBufSize, column, span):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLint, _cs.GLenum, _cs.GLenum, _cs.GLsizei, ctypes.c_void_p)
def glGetnTexImage(target, level, format, type, bufSize, pixels):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLdoubleArray)
def glGetnUniformdv(program, location, bufSize, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLfloatArray)
def glGetnUniformfv(program, location, bufSize, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLintArray)
def glGetnUniformiv(program, location, bufSize, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLuintArray)
def glGetnUniformuiv(program, location, bufSize, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLsizei, arrays.GLuintArray)
def glInvalidateNamedFramebufferData(framebuffer, numAttachments, attachments):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLsizei, arrays.GLuintArray, _cs.GLint, _cs.GLint, _cs.GLsizei, _cs.GLsizei)
def glInvalidateNamedFramebufferSubData(framebuffer, numAttachments, attachments, x, y, width, height):
    ...

@_f
@_p.types(ctypes.c_void_p, _cs.GLuint, _cs.GLenum)
def glMapNamedBuffer(buffer, access):
    ...

@_f
@_p.types(ctypes.c_void_p, _cs.GLuint, _cs.GLintptr, _cs.GLsizeiptr, _cs.GLbitfield)
def glMapNamedBufferRange(buffer, offset, length, access):
    ...

@_f
@_p.types(None, _cs.GLbitfield)
def glMemoryBarrierByRegion(barriers):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLsizeiptr, ctypes.c_void_p, _cs.GLenum)
def glNamedBufferData(buffer, size, data, usage):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLsizeiptr, ctypes.c_void_p, _cs.GLbitfield)
def glNamedBufferStorage(buffer, size, data, flags):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLintptr, _cs.GLsizeiptr, ctypes.c_void_p)
def glNamedBufferSubData(buffer, offset, size, data):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum)
def glNamedFramebufferDrawBuffer(framebuffer, buf):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLsizei, arrays.GLuintArray)
def glNamedFramebufferDrawBuffers(framebuffer, n, bufs):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLint)
def glNamedFramebufferParameteri(framebuffer, pname, param):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum)
def glNamedFramebufferReadBuffer(framebuffer, src):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLenum, _cs.GLuint)
def glNamedFramebufferRenderbuffer(framebuffer, attachment, renderbuffertarget, renderbuffer):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLuint, _cs.GLint)
def glNamedFramebufferTexture(framebuffer, attachment, texture, level):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLuint, _cs.GLint, _cs.GLint)
def glNamedFramebufferTextureLayer(framebuffer, attachment, texture, level, layer):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLsizei, _cs.GLsizei)
def glNamedRenderbufferStorage(renderbuffer, internalformat, width, height):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLsizei, _cs.GLenum, _cs.GLsizei, _cs.GLsizei)
def glNamedRenderbufferStorageMultisample(renderbuffer, samples, internalformat, width, height):
    ...

@_f
@_p.types(None, _cs.GLint, _cs.GLint, _cs.GLsizei, _cs.GLsizei, _cs.GLenum, _cs.GLenum, _cs.GLsizei, ctypes.c_void_p)
def glReadnPixels(x, y, width, height, format, type, bufSize, data):
    ...

@_f
@_p.types(None)
def glTextureBarrier():
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLuint)
def glTextureBuffer(texture, internalformat, buffer):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLuint, _cs.GLintptr, _cs.GLsizeiptr)
def glTextureBufferRange(texture, internalformat, buffer, offset, size):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLintArray)
def glTextureParameterIiv(texture, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLuintArray)
def glTextureParameterIuiv(texture, pname, params):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLfloat)
def glTextureParameterf(texture, pname, param):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLfloatArray)
def glTextureParameterfv(texture, pname, param):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLint)
def glTextureParameteri(texture, pname, param):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLintArray)
def glTextureParameteriv(texture, pname, param):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLsizei, _cs.GLenum, _cs.GLsizei)
def glTextureStorage1D(texture, levels, internalformat, width):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLsizei, _cs.GLenum, _cs.GLsizei, _cs.GLsizei)
def glTextureStorage2D(texture, levels, internalformat, width, height):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLsizei, _cs.GLenum, _cs.GLsizei, _cs.GLsizei, _cs.GLboolean)
def glTextureStorage2DMultisample(texture, samples, internalformat, width, height, fixedsamplelocations):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLsizei, _cs.GLenum, _cs.GLsizei, _cs.GLsizei, _cs.GLsizei)
def glTextureStorage3D(texture, levels, internalformat, width, height, depth):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLsizei, _cs.GLenum, _cs.GLsizei, _cs.GLsizei, _cs.GLsizei, _cs.GLboolean)
def glTextureStorage3DMultisample(texture, samples, internalformat, width, height, depth, fixedsamplelocations):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLint, _cs.GLsizei, _cs.GLenum, _cs.GLenum, ctypes.c_void_p)
def glTextureSubImage1D(texture, level, xoffset, width, format, type, pixels):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLsizei, _cs.GLsizei, _cs.GLenum, _cs.GLenum, ctypes.c_void_p)
def glTextureSubImage2D(texture, level, xoffset, yoffset, width, height, format, type, pixels):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLsizei, _cs.GLsizei, _cs.GLsizei, _cs.GLenum, _cs.GLenum, ctypes.c_void_p)
def glTextureSubImage3D(texture, level, xoffset, yoffset, zoffset, width, height, depth, format, type, pixels):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLuint)
def glTransformFeedbackBufferBase(xfb, index, buffer):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLuint, _cs.GLintptr, _cs.GLsizeiptr)
def glTransformFeedbackBufferRange(xfb, index, buffer, offset, size):
    ...

@_f
@_p.types(_cs.GLboolean, _cs.GLuint)
def glUnmapNamedBuffer(buffer):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLuint)
def glVertexArrayAttribBinding(vaobj, attribindex, bindingindex):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLint, _cs.GLenum, _cs.GLboolean, _cs.GLuint)
def glVertexArrayAttribFormat(vaobj, attribindex, size, type, normalized, relativeoffset):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLint, _cs.GLenum, _cs.GLuint)
def glVertexArrayAttribIFormat(vaobj, attribindex, size, type, relativeoffset):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLint, _cs.GLenum, _cs.GLuint)
def glVertexArrayAttribLFormat(vaobj, attribindex, size, type, relativeoffset):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLuint)
def glVertexArrayBindingDivisor(vaobj, bindingindex, divisor):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint)
def glVertexArrayElementBuffer(vaobj, buffer):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLuint, _cs.GLintptr, _cs.GLsizei)
def glVertexArrayVertexBuffer(vaobj, bindingindex, buffer, offset, stride):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLuint, _cs.GLsizei, arrays.GLuintArray, ctypes.POINTER(_cs.GLintptr), arrays.GLsizeiArray)
def glVertexArrayVertexBuffers(vaobj, first, count, buffers, offsets, strides):
    ...

