"""
This type stub file was generated by pyright.
"""

from OpenGL.raw import GLU as _simple

"""
This type stub file was generated by pyright.
"""
class GLUQuadric(_simple.GLUquadric):
    """Implementation class for GLUQuadric classes in PyOpenGL"""
    FUNCTION_TYPE = ...
    CALLBACK_TYPES = ...
    def addCallback(self, which, function):
        """Register a callback for the quadric object
        
        At the moment only GLU_ERROR is supported by OpenGL, but
        we allow for the possibility of more callbacks in the future...
        """
        ...
    


GLUquadric = GLUQuadric
def gluQuadricCallback(quadric, which=..., function=...):
    """Set the GLU error callback function"""
    ...

gluNewQuadric = ...
