from _typeshed import Incomplete

class CancelledError(BaseException): ...
class TimeoutError(Exception): ...
class InvalidStateError(Exception): ...
class SendfileNotAvailableError(RuntimeError): ...

class IncompleteReadError(EOFError):
    partial: Incomplete
    expected: Incomplete
    def __init__(self, partial, expected) -> None: ...
    def __reduce__(self): ...

class LimitOverrunError(Exception):
    consumed: Incomplete
    def __init__(self, message, consumed) -> None: ...
    def __reduce__(self): ...
