"""
This type stub file was generated by pyright.
"""

from typing import Any, List

"""
This type stub file was generated by pyright.
"""
__all__: List[str]
run_main: Any
compile: Any
f2py_testing: Any
