"""
This type stub file was generated by pyright.
"""

import sys

"""8-bit string definitions for Python 2/3 compatibility

Defines the following which allow for dealing with Python 3 breakages:

    STR_IS_BYTES
    STR_IS_UNICODE
    
        Easily checked booleans for type identities
    
    _NULL_8_BYTE
    
        An 8-bit byte with NULL (0) value 
    
    as_8_bit( x, encoding='utf-8')
    
        Returns the value as the 8-bit version
    
    unicode -- always pointing to the unicode type 
    bytes -- always pointing to the 8-bit bytes type
"""
STR_IS_BYTES = ...
if sys.version_info[: 2] < (2, 6):
    bytes = ...
else:
    bytes = ...
if sys.version_info[: 2] < (3, 0):
    unicode = ...
    _NULL_8_BYTE = ...
    def as_8_bit(x, encoding=...):
        ...
    
    integer_types = ...
    def as_str(x, encoding=...):
        """Produce a native string (i.e. different on python 2 and 3)"""
        ...
    
else:
    STR_IS_BYTES = ...
    _NULL_8_BYTE = ...
    def as_8_bit(x, encoding=...):
        ...
    
    unicode = ...
    integer_types = ...
    def as_str(x, encoding=...):
        """Produce a native string (i.e. different on python 2 and 3)"""
        ...
    
STR_IS_UNICODE = ...
if hasattr(sys, 'maxsize'):
    maxsize = ...
else:
    maxsize = ...
def as_unicode(x, encoding=...):
    """Ensure is a unicode object given default encoding"""
    ...

