"""
This type stub file was generated by pyright.
"""

import ctypes

"""
This type stub file was generated by pyright.
"""
GLenum = ctypes.c_uint
GLboolean = ctypes.c_ubyte
GLsizei = ctypes.c_int
GLint = ctypes.c_int
OSMesaContext = ...
