# Names in __all__ with no definition:
#   AbortHandshake
#   BasicAuthWebSocketServerProtocol
#   ClientConnection
#   ConnectionClosed
#   ConnectionClosedError
#   ConnectionClosedOK
#   Data
#   DuplicateParameter
#   ExtensionName
#   ExtensionParameter
#   InvalidHandshake
#   InvalidHeader
#   InvalidHeaderFormat
#   InvalidHeaderValue
#   InvalidMessage
#   InvalidOrigin
#   InvalidParameterName
#   InvalidParameterValue
#   InvalidState
#   InvalidStatus
#   InvalidStatusCode
#   InvalidURI
#   InvalidUpgrade
#   LoggerLike
#   NegotiationError
#   Origin
#   PayloadTooBig
#   ProtocolError
#   RedirectHandshake
#   SecurityError
#   ServerConnection
#   Subprotocol
#   WebSocketClientProtocol
#   WebSocketCommonProtocol
#   WebSocketException
#   WebSocketProtocolError
#   WebSocketServer
#   WebSocketServerProtocol
#   WebSocketURI
#   basic_auth_protocol_factory
#   broadcast
#   connect
#   parse_uri
#   serve
#   unix_connect
#   unix_serve
