from _typeshed import Incomplete
from typing import Generator

class StreamReader:
    buffer: Incomplete
    eof: bool
    def __init__(self) -> None: ...
    def read_line(self, m: int) -> Generator[None, None, bytes]: ...
    def read_exact(self, n: int) -> Generator[None, None, bytes]: ...
    def read_to_eof(self, m: int) -> Generator[None, None, bytes]: ...
    def at_eof(self) -> Generator[None, None, bool]: ...
    def feed_data(self, data: bytes) -> None: ...
    def feed_eof(self) -> None: ...
    def discard(self) -> None: ...
