"""
This type stub file was generated by pyright.
"""

import os
import sys
from OpenGL.plugins import PlatformPlugin
from OpenGL import _configflags

"""Abstraction for the platform-specific code in PyOpenGL

Each supported platform has a module which provides the
specific functionality required to support the base OpenGL 
functionality on that platform.  These modules are 
registered using plugins in the:

    OpenGL.plugin.PlatformPlugin

objects.  To support a new platform you'll need to create
a new PlatformPlugin instance *before* you import 
OpenGL.platform .  Once you have a working platform 
module, please consider contributing it back to the project.

See baseplatform.BasePlatform for the core functionality 
of a platform implementation.  See the various platform 
specific modules for examples to use when porting.
"""
def types(resultType, *argTypes):
    """Decorator to add returnType, argTypes and argNames to a function"""
    ...

def unpack_constants(constants, namespace):
    """Create constants and add to the namespace"""
    ...

def createFunction(function, dll, extension, deprecated=..., error_checker=..., force_extension=...):
    """Allows the more compact declaration format to use the old-style constructor"""
    ...

