# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\nVisualizer\"G\n\x0bMessageData\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.Visualizer.DataType\x12\t\n\x01x\x18\x02 \x03(\x02\x12\t\n\x01y\x18\x03 \x03(\x02\"A\n\x0b\x44\x61taRequest\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\"\n\x04type\x18\x02 \x01(\x0e\x32\x14.Visualizer.DataType*$\n\x08\x44\x61taType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07LRFDATA\x10\x01\x62\x06proto3')

_DATATYPE = DESCRIPTOR.enum_types_by_name['DataType']
DataType = enum_type_wrapper.EnumTypeWrapper(_DATATYPE)
UNKNOWN = 0
LRFDATA = 1


_MESSAGEDATA = DESCRIPTOR.message_types_by_name['MessageData']
_DATAREQUEST = DESCRIPTOR.message_types_by_name['DataRequest']
MessageData = _reflection.GeneratedProtocolMessageType('MessageData', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEDATA,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:Visualizer.MessageData)
  })
_sym_db.RegisterMessage(MessageData)

DataRequest = _reflection.GeneratedProtocolMessageType('DataRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATAREQUEST,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:Visualizer.DataRequest)
  })
_sym_db.RegisterMessage(DataRequest)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATATYPE._serialized_start=169
  _DATATYPE._serialized_end=205
  _MESSAGEDATA._serialized_start=29
  _MESSAGEDATA._serialized_end=100
  _DATAREQUEST._serialized_start=102
  _DATAREQUEST._serialized_end=167
# @@protoc_insertion_point(module_scope)
