[tool.pyright]

include = ["."]
exclude = ["**/node_modules",
    "**/__pycache__",
    ".git",
]

stubPath = "./stubs"

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.6"
pythonPlatform = "Darwin"

executionEnvironments = []
