from ..datastructures import Headers

def build_request(headers: Headers) -> str: ...
def check_request(headers: Headers) -> str: ...
def build_response(headers: Headers, key: str) -> None: ...
def check_response(headers: Headers, key: str) -> None: ...
