"""
This type stub file was generated by pyright.
"""

from typing import List

"""
This type stub file was generated by pyright.
"""
__all__: List[str]
def pad(array, pad_width, mode=..., **kwargs):
    ...

