"""
This type stub file was generated by pyright.
"""

from typing import Any, Generator, List, Tuple, overload
from numpy import dtype, ndarray
from numpy.typing import DTypeLike

"""
This type stub file was generated by pyright.
"""
_Shape = ...
_DType = ...
_ScalarType = ...
_Index = ...
__all__: List[str]
class Arrayterator(ndarray[_Shape, _DType]):
    var: ndarray[_Shape, _DType]
    buf_size: None | int
    start: List[int]
    stop: List[int]
    step: List[int]
    @property
    def shape(self) -> Tuple[int, ...]:
        ...
    
    @property
    def flat(self: ndarray[Any, dtype[_ScalarType]]) -> Generator[_ScalarType, None, None]:
        ...
    
    def __init__(self, var: ndarray[_Shape, _DType], buf_size: None | int = ...) -> None:
        ...
    
    @overload
    def __array__(self, dtype: None = ...) -> ndarray[Any, _DType]:
        ...
    
    @overload
    def __array__(self, dtype: DTypeLike) -> ndarray[Any, dtype[Any]]:
        ...
    
    def __getitem__(self, index: _Index) -> Arrayterator[Any, _DType]:
        ...
    
    def __iter__(self) -> Generator[ndarray[Any, _DType], None, None]:
        ...
    


