"""
This type stub file was generated by pyright.
"""

from typing import List

"""
This type stub file was generated by pyright.
"""
__all__: List[str]
def poly(seq_of_zeros):
    ...

def roots(p):
    ...

def polyint(p, m=..., k=...):
    ...

def polyder(p, m=...):
    ...

def polyfit(x, y, deg, rcond=..., full=..., w=..., cov=...):
    ...

def polyval(p, x):
    ...

def polyadd(a1, a2):
    ...

def polysub(a1, a2):
    ...

def polymul(a1, a2):
    ...

def polydiv(u, v):
    ...

