"""
This type stub file was generated by pyright.
"""

from typing import Any, List
from numpy.typing import _Shape, _ShapeLike

"""
This type stub file was generated by pyright.
"""
__all__: List[str]
class DummyArray:
    __array_interface__: Any
    base: Any
    def __init__(self, interface, base=...) -> None:
        ...
    


def as_strided(x, shape=..., strides=..., subok=..., writeable=...):
    ...

def sliding_window_view(x, window_shape, axis=..., *, subok=..., writeable=...):
    ...

def broadcast_to(array, shape, subok=...):
    ...

def broadcast_shapes(*args: _ShapeLike) -> _Shape:
    ...

def broadcast_arrays(*args, subok=...):
    ...

