"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Union, overload
from numpy import bool_, floating, object_
from numpy.typing import NDArray, _ArrayLikeFloat_co, _ArrayLikeObject_co, _FloatLike_co

"""
This type stub file was generated by pyright.
"""
_ArrayType = ...
__all__: List[str]
@overload
def fix(x: _FloatLike_co, out: None = ...) -> floating[Any]:
    ...

@overload
def fix(x: _ArrayLikeFloat_co, out: None = ...) -> NDArray[floating[Any]]:
    ...

@overload
def fix(x: _ArrayLikeObject_co, out: None = ...) -> NDArray[object_]:
    ...

@overload
def fix(x: Union[_ArrayLikeFloat_co, _ArrayLikeObject_co], out: _ArrayType) -> _ArrayType:
    ...

@overload
def isposinf(x: _FloatLike_co, out: None = ...) -> bool_:
    ...

@overload
def isposinf(x: _ArrayLikeFloat_co, out: None = ...) -> NDArray[bool_]:
    ...

@overload
def isposinf(x: _ArrayLikeFloat_co, out: _ArrayType) -> _ArrayType:
    ...

@overload
def isneginf(x: _FloatLike_co, out: None = ...) -> bool_:
    ...

@overload
def isneginf(x: _ArrayLikeFloat_co, out: None = ...) -> NDArray[bool_]:
    ...

@overload
def isneginf(x: _ArrayLikeFloat_co, out: _ArrayType) -> _ArrayType:
    ...

