"""
This type stub file was generated by pyright.
"""

from datetime import date as real_date, datetime as real_datetime, time as real_time

class date(real_date):
    def strftime(self, fmt):
        ...
    


class datetime(real_datetime):
    def strftime(self, fmt):
        ...
    
    @classmethod
    def combine(cls, date, time):
        ...
    
    def date(self):
        ...
    


class time(real_time):
    ...


def new_date(d):
    "Generate a safe date from a datetime.date object."
    ...

def new_datetime(d):
    """
    Generate a safe datetime from a datetime.date or datetime.datetime object.
    """
    ...

_illegal_formatting = ...
def strftime(dt, fmt):
    ...

