"""
This type stub file was generated by pyright.
"""

from typing import Any, List
from numpy import matrix as matrix

"""
This type stub file was generated by pyright.
"""
__all__: List[str]
def bmat(obj, ldict=..., gdict=...):
    ...

def asmatrix(data, dtype=...):
    ...

mat = ...
