"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GLES2._types import *
from OpenGL.platform import PLATFORM as _p

"""
This type stub file was generated by pyright.
"""
_error_function = getattr(_p.GLES3, 'glGetError', None)
