"""
This type stub file was generated by pyright.
"""

from OpenGL.error import EGLError, _ErrorChecker

"""
This type stub file was generated by pyright.
"""
class EGLError(EGLError):
    @property
    def err(self):
        ...
    
    @err.setter
    def err(self, value):
        ...
    


if _ErrorChecker:
    _error_checker = ...
else:
    _ErrorChecker = ...
