"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GLE import *
from OpenGL.raw.GLE.annotations import *
from OpenGL.GLE.exceptional import *

"""GL Extrusion Routine Library (GLE) wrapper for OpenGL-ctypes"""
