"""
This type stub file was generated by pyright.
"""

import ctypes

"""
This type stub file was generated by pyright.
"""
pointer = ctypes.pointer
class _Opaque(ctypes.Structure):
    """An Opaque Structure reference (base class)"""
    ...


class _opaque_pointer(ctypes.POINTER(_Opaque)):
    _type_ = _Opaque
    @classmethod
    def from_param(cls, value):
        ...
    
    @property
    def address(self):
        ...
    
    @property
    def as_voidp(self):
        ...
    
    def __hash__(self) -> int:
        """Allow these pointers to be used as keys in dictionaries"""
        ...
    


def opaque_pointer_cls(name):
    """Create an Opaque pointer class for the given name"""
    ...

