"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.GL._types import *
from OpenGL.arrays._arrayconstants import *

"""Backward-compatibility module to provide core-GL constant names"""
