"""
This type stub file was generated by pyright.
"""

import numpy as np

''' Utilities to allow inserting docstring fragments for common
parameters into function and method docstrings'''
@np.deprecate(message="scipy.misc.docformat is deprecated in Scipy 1.3.0")
def docformat(docstring, docdict=...):
    ...

@np.deprecate(message="scipy.misc.inherit_docstring_from is deprecated " "in SciPy 1.3.0")
def inherit_docstring_from(cls): # -> (func: Unknown) -> Unknown:
    ...

@np.deprecate(message="scipy.misc.extend_notes_in_docstring is deprecated " "in SciPy 1.3.0")
def extend_notes_in_docstring(cls, notes): # -> (func: Unknown) -> Unknown:
    ...

@np.deprecate(message="scipy.misc.replace_notes_in_docstring is deprecated " "in SciPy 1.3.0")
def replace_notes_in_docstring(cls, notes): # -> (func: Unknown) -> Unknown:
    ...

@np.deprecate(message="scipy.misc.indentcount_lines is deprecated " "in SciPy 1.3.0")
def indentcount_lines(lines): # -> int:
    ...

@np.deprecate(message="scipy.misc.filldoc is deprecated in SciPy 1.3.0")
def filldoc(docdict, unindent_params=...): # -> (f: Unknown) -> Unknown:
    ...

@np.deprecate(message="scipy.misc.unindent_dict is deprecated in SciPy 1.3.0")
def unindent_dict(docdict): # -> dict[Unknown, Unknown]:
    ...

@np.deprecate(message="scipy.misc.unindent_string is deprecated in SciPy 1.3.0")
def unindent_string(docstring): # -> str:
    ...

