"""
This type stub file was generated by pyright.
"""

import sys
from typing import Protocol, TYPE_CHECKING, overload
from numpy import ndarray
from ._dtype_like import DTypeLike

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 8):
    HAVE_PROTOCOL = ...
else:
    ...
if TYPE_CHECKING or HAVE_PROTOCOL:
    class _SupportsArray(Protocol):
        @overload
        def __array__(self, __dtype: DTypeLike = ...) -> ndarray:
            ...
        
        @overload
        def __array__(self, dtype: DTypeLike = ...) -> ndarray:
            ...
        
    
    
else:
    ...
ArrayLike = ...
