"""
This type stub file was generated by pyright.
"""

import sys
from typing import Any, Protocol, Sequence, TYPE_CHECKING, TypedDict
from numpy import dtype

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 8):
    HAVE_PROTOCOL = ...
else:
    ...
_DTypeLikeNested = Any
if TYPE_CHECKING or HAVE_PROTOCOL:
    class _DTypeDictBase(TypedDict):
        names: Sequence[str]
        formats: Sequence[_DTypeLikeNested]
        ...
    
    
    class _DTypeDict(_DTypeDictBase, total=False):
        offsets: Sequence[int]
        titles: Sequence[Any]
        itemsize: int
        aligned: bool
        ...
    
    
    class _SupportsDType(Protocol):
        dtype: _DTypeLikeNested
        ...
    
    
else:
    ...
_VoidDTypeLike = ...
DTypeLike = ...
