"""
This type stub file was generated by pyright.
"""

import numpy as np
from typing import Any, Tuple, Union

"""
This type stub file was generated by pyright.
"""
_CharLike = Union[str, bytes]
_BoolLike = Union[bool, np.bool_]
_IntLike = Union[int, np.integer]
_FloatLike = Union[_IntLike, float, np.floating]
_ComplexLike = Union[_FloatLike, complex, np.complexfloating]
_NumberLike = Union[int, float, complex, np.number, np.bool_]
_ScalarLike = ...
_VoidLike = Union[Tuple[Any, ...], np.void]
