"""
This type stub file was generated by pyright.
"""

from typing import Sequence, TYPE_CHECKING, Tuple, Union

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
_Shape = Tuple[int, ...]
_ShapeLike = Union["SupportsIndex", Sequence["SupportsIndex"]]
