"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def uintToLong(value):
    ...

class GLSelectRecord(object):
    """Minimalist object for storing an OpenGL selection-buffer record
    
    Provides near and far as *float* values by dividing by 
    self.DISTANCE_DIVISOR (2**32-1)
    From the spec:
        Depth values (which are in the range [0,1]) are multiplied by 
        2^32 - 1, before being placed in the hit record.
    
    Names are unmodified, so normally are slices of the array passed in 
    to GLSelectRecord.fromArray( array )
    """
    DISTANCE_DIVISOR = ...
    __slots__ = ...
    def fromArray(cls, array, total):
        """Produce list with all records from the array"""
        ...
    
    fromArray = ...
    def __init__(self, near, far, names) -> None:
        """Initialise/store the values"""
        ...
    
    def convertDistance(self, value):
        """Convert a distance value from array uint to 0.0-1.0 range float"""
        ...
    
    def __getitem__(self, key):
        """Allow for treating the record as a three-tuple"""
        ...
    


