"""
This type stub file was generated by pyright.
"""

from django.core.serializers import base

"""
A Python "serializer". Doesn't do much serializing per se -- just converts to
and from basic Python data types (lists, dicts, strings, etc.). Useful as a basis for
other serializers.
"""
class Serializer(base.Serializer):
    """
    Serialize a QuerySet to basic Python objects.
    """
    internal_use_only = ...
    def start_serialization(self):
        ...
    
    def end_serialization(self):
        ...
    
    def start_object(self, obj):
        ...
    
    def end_object(self, obj):
        ...
    
    def get_dump_object(self, obj):
        ...
    
    def handle_field(self, obj, field):
        ...
    
    def handle_fk_field(self, obj, field):
        ...
    
    def handle_m2m_field(self, obj, field):
        ...
    
    def getvalue(self):
        ...
    


def Deserializer(object_list, *, using=..., ignorenonexistent=..., **options):
    """
    Deserialize simple Python objects back into Django ORM instances.

    It's expected that you pass the Python objects themselves (instead of a
    stream or a string) to the constructor
    """
    ...

