"""
This type stub file was generated by pyright.
"""

from collections import UserList
from django.utils.html import html_safe

def pretty_name(name):
    """Convert 'first_name' to 'First name'."""
    ...

def flatatt(attrs):
    """
    Convert a dictionary of attributes to a single string.
    The returned string will contain a leading space followed by key="value",
    XML-style pairs. In the case of a boolean value, the key will appear
    without a value. It is assumed that the keys do not need to be
    XML-escaped. If the passed dictionary is empty, then return an empty
    string.

    The result is passed through 'mark_safe' (by way of 'format_html_join').
    """
    ...

@html_safe
class ErrorDict(dict):
    """
    A collection of errors that knows how to display itself in various formats.

    The dictionary keys are the field names, and the values are the errors.
    """
    def as_data(self):
        ...
    
    def get_json_data(self, escape_html=...):
        ...
    
    def as_json(self, escape_html=...):
        ...
    
    def as_ul(self):
        ...
    
    def as_text(self):
        ...
    
    def __str__(self) -> str:
        ...
    


@html_safe
class ErrorList(UserList, list):
    """
    A collection of errors that knows how to display itself in various formats.
    """
    def __init__(self, initlist=..., error_class=...) -> None:
        ...
    
    def as_data(self):
        ...
    
    def copy(self):
        ...
    
    def get_json_data(self, escape_html=...):
        ...
    
    def as_json(self, escape_html=...):
        ...
    
    def as_ul(self):
        ...
    
    def as_text(self):
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self):
        ...
    
    def __contains__(self, item):
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __getitem__(self, i):
        ...
    
    def __reduce_ex__(self, *args, **kwargs):
        ...
    


def from_current_timezone(value):
    """
    When time zone support is enabled, convert naive datetimes
    entered in the current time zone to aware datetimes.
    """
    ...

def to_current_timezone(value):
    """
    When time zone support is enabled, convert aware datetimes
    to naive datetimes in the current time zone for display.
    """
    ...

