"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class GLUStruct(object):
    """Mix-in class for GLU Structures that want to retain references to callbacks
    
    Also provides original-object-return for the "datapointer" style paremters
    
    Each sub-class must override:
        CALLBACK_TYPES -- maps a "which" constant to a function type 
        CALLBACK_FUNCTION_REGISTRARS -- maps a "which" constant to the 
            registration function for functions of that type
        WRAPPER_METHODS -- maps a "which" consant to a method of the structure 
            that produces a callable around the function which takes care of 
            input/output arguments, data conversions, error handling and the 
            like.
    Creates a dictionary member dataPointers if original-object-return is used
    Creates a dictionary member callbacks if callback registration is used
    """
    def getAsParam(self):
        """Gets as a ctypes pointer to the underlying structure"""
        ...
    
    _as_parameter_ = ...
    CALLBACK_TYPES = ...
    CALLBACK_FUNCTION_REGISTRARS = ...
    WRAPPER_METHODS = ...
    def noteObject(self, object):
        """Note object for later retrieval as a Python object pointer
        
        This is the registration point for "original object return", returns 
        a void pointer to the Python object, though this is, effectively, an 
        opaque value.
        """
        ...
    
    def originalObject(self, voidPointer):
        """Given a void-pointer, try to find our original Python object"""
        ...
    
    def addCallback(self, which, function):
        """Register a callback for this structure object"""
        ...
    
    def ptrAsArray(self, ptr, length, type):
        """Copy length values from ptr into new array of given type"""
        ...
    


