"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.EGL.VERSION.EGL_1_5 import *

"""
This type stub file was generated by pyright.
"""
def glInitEgl15VERSION():
    '''Return boolean indicating whether this extension is available'''
    ...

eglGetPlatformDisplay = ...
