"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.EGL.VERSION.EGL_1_2 import *

"""
This type stub file was generated by pyright.
"""
def glInitEgl12VERSION():
    '''Return boolean indicating whether this extension is available'''
    ...

