"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.EGL.VERSION.EGL_1_1 import *

"""
This type stub file was generated by pyright.
"""
def glInitEgl11VERSION():
    '''Return boolean indicating whether this extension is available'''
    ...

