"""
This type stub file was generated by pyright.
"""

import ctypes
from OpenGL import arrays, platform as _p
from OpenGL.raw.GL import _types as _cs
from OpenGL.raw.GL._types import *

"""
This type stub file was generated by pyright.
"""
_EXTENSION_NAME = ...
GL_ACTIVE_PROGRAM = ...
GL_ALL_SHADER_BITS = ...
GL_FIXED = ...
GL_FRAGMENT_SHADER_BIT = ...
GL_GEOMETRY_SHADER_BIT = ...
GL_HIGH_FLOAT = ...
GL_HIGH_INT = ...
GL_IMPLEMENTATION_COLOR_READ_FORMAT = ...
GL_IMPLEMENTATION_COLOR_READ_TYPE = ...
GL_LAYER_PROVOKING_VERTEX = ...
GL_LOW_FLOAT = ...
GL_LOW_INT = ...
GL_MAX_FRAGMENT_UNIFORM_VECTORS = ...
GL_MAX_VARYING_VECTORS = ...
GL_MAX_VERTEX_UNIFORM_VECTORS = ...
GL_MAX_VIEWPORTS = ...
GL_MEDIUM_FLOAT = ...
GL_MEDIUM_INT = ...
GL_NUM_PROGRAM_BINARY_FORMATS = ...
GL_NUM_SHADER_BINARY_FORMATS = ...
GL_PROGRAM_BINARY_FORMATS = ...
GL_PROGRAM_BINARY_LENGTH = ...
GL_PROGRAM_BINARY_RETRIEVABLE_HINT = ...
GL_PROGRAM_PIPELINE_BINDING = ...
GL_PROGRAM_SEPARABLE = ...
GL_RGB565 = ...
GL_SHADER_BINARY_FORMATS = ...
GL_SHADER_COMPILER = ...
GL_TESS_CONTROL_SHADER_BIT = ...
GL_TESS_EVALUATION_SHADER_BIT = ...
GL_UNDEFINED_VERTEX = ...
GL_VERTEX_SHADER_BIT = ...
GL_VIEWPORT_BOUNDS_RANGE = ...
GL_VIEWPORT_INDEX_PROVOKING_VERTEX = ...
GL_VIEWPORT_SUBPIXEL_BITS = ...
@_f
@_p.types(None, _cs.GLuint, _cs.GLuint)
def glActiveShaderProgram(pipeline, program):
    ...

@_f
@_p.types(None, _cs.GLuint)
def glBindProgramPipeline(pipeline):
    ...

@_f
@_p.types(None, _cs.GLfloat)
def glClearDepthf(d):
    ...

@_f
@_p.types(_cs.GLuint, _cs.GLenum, _cs.GLsizei, ctypes.POINTER(ctypes.POINTER(_cs.GLchar)))
def glCreateShaderProgramv(type, count, strings):
    ...

@_f
@_p.types(None, _cs.GLsizei, arrays.GLuintArray)
def glDeleteProgramPipelines(n, pipelines):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLsizei, arrays.GLdoubleArray)
def glDepthRangeArrayv(first, count, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLdouble, _cs.GLdouble)
def glDepthRangeIndexed(index, n, f):
    ...

@_f
@_p.types(None, _cs.GLfloat, _cs.GLfloat)
def glDepthRangef(n, f):
    ...

@_f
@_p.types(None, _cs.GLsizei, arrays.GLuintArray)
def glGenProgramPipelines(n, pipelines):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLuint, arrays.GLdoubleArray)
def glGetDoublei_v(target, index, data):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLuint, arrays.GLfloatArray)
def glGetFloati_v(target, index, data):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLsizei, arrays.GLsizeiArray, arrays.GLuintArray, ctypes.c_void_p)
def glGetProgramBinary(program, bufSize, length, binaryFormat, binary):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLsizei, arrays.GLsizeiArray, arrays.GLcharArray)
def glGetProgramPipelineInfoLog(pipeline, bufSize, length, infoLog):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLintArray)
def glGetProgramPipelineiv(pipeline, pname, params):
    ...

@_f
@_p.types(None, _cs.GLenum, _cs.GLenum, arrays.GLintArray, arrays.GLintArray)
def glGetShaderPrecisionFormat(shadertype, precisiontype, range, precision):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, arrays.GLdoubleArray)
def glGetVertexAttribLdv(index, pname, params):
    ...

@_f
@_p.types(_cs.GLboolean, _cs.GLuint)
def glIsProgramPipeline(pipeline):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, ctypes.c_void_p, _cs.GLsizei)
def glProgramBinary(program, binaryFormat, binary, length):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLint)
def glProgramParameteri(program, pname, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLenum, _cs.GLint)
def glProgramParameteri(program, pname, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLdouble)
def glProgramUniform1d(program, location, v0):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLdoubleArray)
def glProgramUniform1dv(program, location, count, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLfloat)
def glProgramUniform1f(program, location, v0):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLfloatArray)
def glProgramUniform1fv(program, location, count, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLint)
def glProgramUniform1i(program, location, v0):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLintArray)
def glProgramUniform1iv(program, location, count, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLuint)
def glProgramUniform1ui(program, location, v0):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLuintArray)
def glProgramUniform1uiv(program, location, count, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLdouble, _cs.GLdouble)
def glProgramUniform2d(program, location, v0, v1):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLdoubleArray)
def glProgramUniform2dv(program, location, count, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLfloat, _cs.GLfloat)
def glProgramUniform2f(program, location, v0, v1):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLfloatArray)
def glProgramUniform2fv(program, location, count, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLint, _cs.GLint)
def glProgramUniform2i(program, location, v0, v1):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLintArray)
def glProgramUniform2iv(program, location, count, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLuint, _cs.GLuint)
def glProgramUniform2ui(program, location, v0, v1):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLuintArray)
def glProgramUniform2uiv(program, location, count, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLdouble, _cs.GLdouble, _cs.GLdouble)
def glProgramUniform3d(program, location, v0, v1, v2):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLdoubleArray)
def glProgramUniform3dv(program, location, count, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLfloat, _cs.GLfloat, _cs.GLfloat)
def glProgramUniform3f(program, location, v0, v1, v2):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLfloatArray)
def glProgramUniform3fv(program, location, count, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint)
def glProgramUniform3i(program, location, v0, v1, v2):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLintArray)
def glProgramUniform3iv(program, location, count, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLuint, _cs.GLuint, _cs.GLuint)
def glProgramUniform3ui(program, location, v0, v1, v2):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLuintArray)
def glProgramUniform3uiv(program, location, count, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLdouble, _cs.GLdouble, _cs.GLdouble, _cs.GLdouble)
def glProgramUniform4d(program, location, v0, v1, v2, v3):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLdoubleArray)
def glProgramUniform4dv(program, location, count, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLfloat, _cs.GLfloat, _cs.GLfloat, _cs.GLfloat)
def glProgramUniform4f(program, location, v0, v1, v2, v3):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLfloatArray)
def glProgramUniform4fv(program, location, count, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint, _cs.GLint)
def glProgramUniform4i(program, location, v0, v1, v2, v3):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLintArray)
def glProgramUniform4iv(program, location, count, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLuint, _cs.GLuint, _cs.GLuint, _cs.GLuint)
def glProgramUniform4ui(program, location, v0, v1, v2, v3):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, arrays.GLuintArray)
def glProgramUniform4uiv(program, location, count, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLdoubleArray)
def glProgramUniformMatrix2dv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLfloatArray)
def glProgramUniformMatrix2fv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLdoubleArray)
def glProgramUniformMatrix2x3dv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLfloatArray)
def glProgramUniformMatrix2x3fv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLdoubleArray)
def glProgramUniformMatrix2x4dv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLfloatArray)
def glProgramUniformMatrix2x4fv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLdoubleArray)
def glProgramUniformMatrix3dv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLfloatArray)
def glProgramUniformMatrix3fv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLdoubleArray)
def glProgramUniformMatrix3x2dv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLfloatArray)
def glProgramUniformMatrix3x2fv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLdoubleArray)
def glProgramUniformMatrix3x4dv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLfloatArray)
def glProgramUniformMatrix3x4fv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLdoubleArray)
def glProgramUniformMatrix4dv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLfloatArray)
def glProgramUniformMatrix4fv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLdoubleArray)
def glProgramUniformMatrix4x2dv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLfloatArray)
def glProgramUniformMatrix4x2fv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLdoubleArray)
def glProgramUniformMatrix4x3dv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLsizei, _cs.GLboolean, arrays.GLfloatArray)
def glProgramUniformMatrix4x3fv(program, location, count, transpose, value):
    ...

@_f
@_p.types(None)
def glReleaseShaderCompiler():
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLsizei, arrays.GLintArray)
def glScissorArrayv(first, count, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLint, _cs.GLsizei, _cs.GLsizei)
def glScissorIndexed(index, left, bottom, width, height):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLintArray)
def glScissorIndexedv(index, v):
    ...

@_f
@_p.types(None, _cs.GLsizei, arrays.GLuintArray, _cs.GLenum, ctypes.c_void_p, _cs.GLsizei)
def glShaderBinary(count, shaders, binaryformat, binary, length):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLbitfield, _cs.GLuint)
def glUseProgramStages(pipeline, stages, program):
    ...

@_f
@_p.types(None, _cs.GLuint)
def glValidateProgramPipeline(pipeline):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLdouble)
def glVertexAttribL1d(index, x):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLdoubleArray)
def glVertexAttribL1dv(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLdouble, _cs.GLdouble)
def glVertexAttribL2d(index, x, y):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLdoubleArray)
def glVertexAttribL2dv(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLdouble, _cs.GLdouble, _cs.GLdouble)
def glVertexAttribL3d(index, x, y, z):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLdoubleArray)
def glVertexAttribL3dv(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLdouble, _cs.GLdouble, _cs.GLdouble, _cs.GLdouble)
def glVertexAttribL4d(index, x, y, z, w):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLdoubleArray)
def glVertexAttribL4dv(index, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLint, _cs.GLenum, _cs.GLsizei, ctypes.c_void_p)
def glVertexAttribLPointer(index, size, type, stride, pointer):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLsizei, arrays.GLfloatArray)
def glViewportArrayv(first, count, v):
    ...

@_f
@_p.types(None, _cs.GLuint, _cs.GLfloat, _cs.GLfloat, _cs.GLfloat, _cs.GLfloat)
def glViewportIndexedf(index, x, y, w, h):
    ...

@_f
@_p.types(None, _cs.GLuint, arrays.GLfloatArray)
def glViewportIndexedfv(index, v):
    ...

