"""
This type stub file was generated by pyright.
"""

from OpenGL.raw.EGL.VERSION.EGL_1_3 import *

'''OpenGL extension VERSION.EGL_1_3

This module customises the behaviour of the 
OpenGL.raw.EGL.VERSION.EGL_1_3 to provide a more 
Python-friendly API

The official definition of this extension is available here:
http://www.opengl.org/registry/specs/VERSION/EGL_1_3.txt
'''
def glInitEgl13VERSION():
    '''Return boolean indicating whether this extension is available'''
    ...

